from __future__ import annotations

from pathlib import Path


def put(path: str, lines: list[str], *, append: bool = False) -> None:
    target = Path(path)
    target.parent.mkdir(parents=True, exist_ok=True)
    mode = "a" if append else "w"
    with target.open(mode, encoding="utf-8", newline="") as handle:
        handle.writelines(lines)


put('.dockerignore', [
    '.git\n',
    '.github\n',
    '.venv\n',
    '__pycache__\n',
    '.pytest_cache\n',
    '.ruff_cache\n',
    '*.pyc\n',
    '*.pyo\n',
    '*.egg-info\n',
    'dist\n',
    'build\n',
    'benchmark-results\n',
    'sgchords-output\n',
    'tests\n',
    'benchmarks/timelines\n',
    '*.wav\n',
    '*.mp3\n',
    '*.m4a\n',
    '*.flac\n',
    '*.ogg\n',
    '*.webm\n',
    '*.mp4\n',
], append=False)

put('.gitignore', [
    '__pycache__/\n',
    '*.py[cod]\n',
    '*.egg-info/\n',
    '.pytest_cache/\n',
    '.ruff_cache/\n',
    '.coverage\n',
    'htmlcov/\n',
    '.venv/\n',
    'venv/\n',
    'dist/\n',
    'build/\n',
    'sgchords-output/\n',
    'benchmark-results/\n',
    'src/sgchords/ui.pyi\n',
    '*.wav\n',
    '*.mp3\n',
    '*.m4a\n',
    '*.flac\n',
    '*.ogg\n',
    '*.webm\n',
    '*.mp4\n',
    '.DS_Store\n',
], append=False)

put('.python-version', [
    '3.12\n',
], append=False)

put('Dockerfile', [
    'FROM python:3.12-slim\n',
    '\n',
    'COPY --from=ghcr.io/astral-sh/uv:0.11.29 /uv /uvx /bin/\n',
    '\n',
    'ENV PYTHONDONTWRITEBYTECODE=1 \\\n',
    '    PYTHONUNBUFFERED=1 \\\n',
    '    UV_COMPILE_BYTECODE=1 \\\n',
    '    UV_LINK_MODE=copy \\\n',
    '    GRADIO_SERVER_NAME=0.0.0.0 \\\n',
    '    GRADIO_SERVER_PORT=7860\n',
    '\n',
    'RUN apt-get update \\\n',
    '    && apt-get install -y --no-install-recommends ffmpeg nodejs \\\n',
    '    && rm -rf /var/lib/apt/lists/*\n',
    '\n',
    'WORKDIR /app\n',
    'COPY pyproject.toml uv.lock README.md LICENSE app.py ./\n',
    'COPY src ./src\n',
    'RUN uv sync --locked --no-dev --no-editable\n',
    '\n',
    'EXPOSE 7860\n',
    'CMD ["/app/.venv/bin/sgchords-web"]\n',
], append=False)

put('README.md', [
    '# SgChords\n',
    '\n',
    'SgChords turns a YouTube link or an uploaded recording into a synchronized, editable guitar or ukulele play-along chart. It runs locally, uses `uv`, and does not require a paid API or a large model download.\n',
    '\n',
    'The analyzer is intentionally honest: automatic chords are a draft. The app exposes confidence, local tonal regions, detected drones, tuning offset, beat and meter confidence, and editable corrections instead of pretending every label is certain.\n',
    '\n',
    '## Highlights\n',
    '\n',
    '### Play along in sync\n',
    '\n',
    '- Current chord, next chord, and countdown update with audio playback.\n',
    '- Click any chord to seek to it.\n',
    '- Double-click a chord and enable looping for focused practice.\n',
    '- Jump backward or forward five seconds.\n',
    '- Practice at 0.75×, 1×, or 1.25× speed without changing pitch.\n',
    '- The chord strip scrolls automatically as the recording plays.\n',
    '\n',
    '### Guitar and ukulele tools\n',
    '\n',
    '- Concert-pitch transposition from −11 to +11 semitones.\n',
    '- Capo shapes without changing the sounding key.\n',
    '- Automatic capo suggestion based on duration-weighted playability.\n',
    '- Standard chord names, Roman numerals, or Nashville numbers.\n',
    '- Inline guitar and ukulele chord diagrams.\n',
    '- Slash-chord and bass-note estimates when the bass is clear.\n',
    '\n',
    '### Better analysis for folk and local music\n',
    '\n',
    '- Beat-synchronous harmonic chroma with tuning correction.\n',
    '- Harmonic-change refinement around beat boundaries.\n',
    '- Local key and mode tracking instead of one global-key assumption.\n',
    '- Major, minor, Dorian, Mixolydian, and Phrygian candidates.\n',
    '- Sustained-drone detection and partial drone suppression before chord scoring.\n',
    '- Meter and downbeat estimates with manual 3-, 4-, or 6-beat override.\n',
    '- Repeated progression detection.\n',
    '- Simple, standard, and detailed chord vocabularies.\n',
    '\n',
    '### Edit and export\n',
    '\n',
    '- Edit chord names, timings, local keys, bars, and beats in a table.\n',
    '- Quantize boundaries to detected beats.\n',
    '- Merge adjacent repeated chords.\n',
    '- Export text, CSV, JSON, ChordPro, chord-shape notes, SRT subtitles, and Audacity/MIREX-style LAB labels.\n',
    '\n',
    '## Requirements\n',
    '\n',
    '- [`uv`](https://docs.astral.sh/uv/) 0.11.29\n',
    '- FFmpeg and FFprobe on `PATH`\n',
    '- A supported JavaScript runtime such as Node.js or Deno for the most reliable current YouTube extraction\n',
    '\n',
    'Only download or process recordings you are allowed to use. YouTube can require authentication, cookies, or regional access, and platform changes can temporarily break automated extraction. Uploading a local file is the most reliable input path.\n',
    '\n',
    '## Install and run with uv\n',
    '\n',
    '```bash\n',
    'git clone https://github.com/Legedith/Sgchords.git\n',
    'cd Sgchords\n',
    'uv sync --locked\n',
    'uv run --frozen sgchords-web\n',
    '```\n',
    '\n',
    'Open `http://127.0.0.1:7860`.\n',
    '\n',
    '`uv sync` creates and manages `.venv`; no manual activation or `pip install` step is required.\n',
    '\n',
    '## Command line\n',
    '\n',
    '```bash\n',
    'uv run --frozen sgchords ./recording.mp3\n',
    'uv run --frozen sgchords ./recording.m4a --instrument ukulele\n',
    'uv run --frozen sgchords ./song.wav --detail detailed --meter 3\n',
    'uv run --frozen sgchords "https://www.youtube.com/watch?v=VIDEO_ID"\n',
    '```\n',
    '\n',
    'Useful options:\n',
    '\n',
    '```text\n',
    '--detail simple|standard|detailed\n',
    '--smoothing 0..1\n',
    '--meter auto|3|4|6\n',
    '--transpose -11..11\n',
    '--capo 0..7\n',
    '--notation standard|roman|nashville\n',
    '--instrument guitar|ukulele\n',
    '```\n',
    '\n',
    'Keep `--transpose 0` when playing with the original recording. Transposition changes the concert key. A capo changes the displayed shapes while preserving the concert pitch.\n',
    '\n',
    '## Docker\n',
    '\n',
    '```bash\n',
    'docker build -t sgchords .\n',
    'docker run --rm -p 7860:7860 sgchords\n',
    '```\n',
    '\n',
    'The image installs from the committed `uv.lock` and includes FFmpeg and Node.js.\n',
    '\n',
    '## Known-chord benchmark\n',
    '\n',
    'The repository includes a reproducible benchmark over five openly licensed recordings whose chord content is stated by the source: two exact C-major progressions, I–V–vi–IV resolving to I, a C–F–G7 guitar clip, and Hotaru no Hikari/Auld Lang Syne.\n',
    '\n',
    '```bash\n',
    'uv run --frozen python scripts/benchmark_known_chords.py --output benchmark-results\n',
    '```\n',
    '\n',
    'See [`benchmarks/README.md`](benchmarks/README.md) for methodology and [`benchmarks/results.md`](benchmarks/results.md) for the latest checked results. Audio is downloaded temporarily and is never committed.\n',
    '\n',
    '## Development\n',
    '\n',
    '```bash\n',
    'uv sync --locked\n',
    'uv run --frozen ruff check .\n',
    'uv run --frozen pytest\n',
    'uv build\n',
    '```\n',
    '\n',
    'When dependencies intentionally change:\n',
    '\n',
    '```bash\n',
    'uv lock\n',
], append=False)
