from __future__ import annotations

from pathlib import Path


def put(path: str, lines: list[str], *, append: bool = False) -> None:
    target = Path(path)
    target.parent.mkdir(parents=True, exist_ok=True)
    mode = "a" if append else "w"
    with target.open(mode, encoding="utf-8", newline="") as handle:
        handle.writelines(lines)


put('src/sgchords/analyzer.py', [
    '    baseline = min(float(np.percentile(mass[active, root], 30)), 0.24)\n',
], append=True)

put('src/sgchords/analyzer.py', [
    '    corrected[:, root] = np.maximum(0.0, corrected[:, root] - 0.58 * baseline)\n',
    '    corrected /= np.maximum(np.sum(corrected, axis=1, keepdims=True), 1e-12)\n',
    '    return root, confidence, corrected * np.sum(matrix, axis=1, keepdims=True)\n',
    '\n',
    '\n',
    'def _key_transition_matrix() -> tuple[tuple, np.ndarray]:\n',
    '    candidates = tonality_candidates()\n',
    '    count = len(candidates)\n',
    '    transition = np.full((count, count), -0.31)\n',
    '    for left_index, left in enumerate(candidates):\n',
    '        for right_index, right in enumerate(candidates):\n',
    '            if left_index == right_index:\n',
    '                transition[left_index, right_index] = 0.04\n',
    '                continue\n',
    '            distance = (right.root - left.root) % 12\n',
    '            penalty = (\n',
    '                -0.09\n',
    '                if left.root == right.root\n',
    '                else -0.15\n',
    '                if distance in {5, 7}\n',
    '                else -0.18\n',
    '                if distance in {3, 4, 8, 9}\n',
    '                else -0.24\n',
    '            )\n',
    '            if left.mode != right.mode:\n',
    '                penalty -= 0.025\n',
    '            transition[left_index, right_index] = penalty\n',
    '    return candidates, transition\n',
    '\n',
    '\n',
    'def _repair_short_runs(\n',
    '    path: np.ndarray, confidence: np.ndarray, boundaries: np.ndarray, minimum: float\n',
    ') -> np.ndarray:\n',
    '    repaired = path.copy()\n',
    '    for _pass in range(8):\n',
    '        runs: list[tuple[int, int, int]] = []\n',
    '        start = 0\n',
    '        for index in range(1, len(repaired) + 1):\n',
    '            if index == len(repaired) or repaired[index] != repaired[start]:\n',
    '                runs.append((start, index, int(repaired[start])))\n',
    '                start = index\n',
    '        changed = False\n',
    '        for run_index, (left, right, _state) in enumerate(runs):\n',
    '            if (\n',
    '                boundaries[right] - boundaries[left] >= minimum\n',
    '                or float(np.mean(confidence[left:right])) >= 0.62\n',
    '            ):\n',
    '                continue\n',
    '            previous = runs[run_index - 1] if run_index else None\n',
    '            following = runs[run_index + 1] if run_index + 1 < len(runs) else None\n',
    '            replacement = None\n',
    '            if previous and following and previous[2] == following[2]:\n',
    '                replacement = previous[2]\n',
    '            elif previous and following:\n',
    '                replacement = (\n',
    '                    previous[2]\n',
    '                    if previous[1] - previous[0] >= following[1] - following[0]\n',
    '                    else following[2]\n',
    '                )\n',
    '            elif previous:\n',
    '                replacement = previous[2]\n',
    '            elif following:\n',
    '                replacement = following[2]\n',
    '            if replacement is not None:\n',
    '                repaired[left:right] = replacement\n',
    '                changed = True\n',
    '                break\n',
    '        if not changed:\n',
    '            break\n',
    '    return repaired\n',
    '\n',
    '\n',
    'def estimate_local_keys(\n',
    '    vectors: np.ndarray,\n',
    '    energies: np.ndarray,\n',
    '    boundaries: np.ndarray,\n',
    '    *,\n',
    '    window_seconds: float = 12.0,\n',
    '    min_region_seconds: float = 4.0,\n',
    ') -> tuple[list[tuple[int, str, float, str]], list[KeyRegion], str, float]:\n',
    '    matrix = np.asarray(vectors, dtype=float)\n',
    '    if matrix.shape[0] == 0:\n',
    '        return [], [], "Unknown", 0.0\n',
    '    centers = (boundaries[:-1] + boundaries[1:]) / 2\n',
    '    durations = np.maximum(boundaries[1:] - boundaries[:-1], 1e-6)\n',
    '    candidates, transition = _key_transition_matrix()\n',
    '    emissions = np.zeros((len(matrix), len(candidates)))\n',
    '    raw_confidence = np.zeros(len(matrix))\n',
    '    median_energy = float(np.median(energies))\n',
    '    for index, center in enumerate(centers):\n',
    '        mask = np.abs(centers - center) <= window_seconds / 2\n',
    '        if np.count_nonzero(mask) < min(4, len(matrix)):\n',
    '            nearest = np.argsort(np.abs(centers - center))[: min(4, len(matrix))]\n',
    '            mask = np.zeros(len(matrix), dtype=bool)\n',
    '            mask[nearest] = True\n',
    '        weights = durations[mask] * np.maximum(energies[mask], median_energy * 0.15 + 1e-8)\n',
    '        aggregate = np.average(matrix[mask], axis=0, weights=weights)\n',
    '        _items, scores = tonality_scores(aggregate)\n',
    '        emissions[index] = scores\n',
    '        order = np.argsort(scores)[::-1]\n',
    '        raw_confidence[index] = np.clip((scores[order[0]] - scores[order[1]]) / 0.18, 0, 1)\n',
    '    dp = np.full_like(emissions, -np.inf)\n',
    '    back = np.zeros_like(emissions, dtype=np.int32)\n',
    '    dp[0] = emissions[0]\n',
    '    for index in range(1, len(matrix)):\n',
    '        options = dp[index - 1][:, None] + transition\n',
    '        back[index] = np.argmax(options, axis=0)\n',
    '        dp[index] = emissions[index] + np.max(options, axis=0)\n',
    '    path = np.zeros(len(matrix), dtype=np.int32)\n',
    '    path[-1] = int(np.argmax(dp[-1]))\n',
    '    for index in range(len(matrix) - 1, 0, -1):\n',
    '        path[index - 1] = back[index, path[index]]\n',
    '    path = _repair_short_runs(path, raw_confidence, boundaries, min_region_seconds)\n',
    '    local = [\n',
    '        (\n',
    '            candidates[int(state)].root,\n',
    '            candidates[int(state)].mode,\n',
    '            float(raw_confidence[index]),\n',
    '            candidates[int(state)].label,\n',
    '        )\n',
    '        for index, state in enumerate(path)\n',
    '    ]\n',
    '    regions: list[KeyRegion] = []\n',
    '    start = 0\n',
    '    for index in range(1, len(path) + 1):\n',
    '        if index < len(path) and path[index] == path[start]:\n',
    '            continue\n',
    '        item = candidates[int(path[start])]\n',
    '        confidence = float(np.average(raw_confidence[start:index], weights=durations[start:index]))\n',
    '        regions.append(\n',
    '            KeyRegion(\n',
    '                float(boundaries[start]),\n',
    '                float(boundaries[index]),\n',
    '                item.label,\n',
    '                confidence,\n',
    '                item.root,\n',
    '                item.mode,\n',
    '            )\n',
    '        )\n',
    '        start = index\n',
    '    totals: dict[str, float] = defaultdict(float)\n',
    '    weighted: dict[str, float] = defaultdict(float)\n',
    '    for region in regions:\n',
    '        totals[region.key] += region.duration\n',
    '        weighted[region.key] += region.duration * region.confidence\n',
    '    dominant = max(totals, key=totals.get)\n',
    '    total_duration = max(float(boundaries[-1] - boundaries[0]), 1e-9)\n',
    '    confidence = float(\n',
    '        np.clip(\n',
    '            (totals[dominant] / total_duration) * weighted[dominant] / max(totals[dominant], 1e-9),\n',
    '            0,\n',
    '            1,\n',
    '        )\n',
    '    )\n',
    '    return local, regions, dominant, confidence\n',
    '\n',
    '\n',
    'def _chord_score(vector: np.ndarray, spec: ChordSpec) -> float:\n',
    '    values = np.maximum(np.asarray(vector, dtype=float), 0.0)\n',
    '    l1 = values / (float(np.sum(values)) + 1e-12)\n',
    '    l2 = values / (float(np.linalg.norm(values)) + 1e-12)\n',
    '    tones = [(spec.root + interval) % 12 for interval in spec.intervals]\n',
    '    coverage = float(np.sum(l1[tones]))\n',
    '    score = (\n',
    '        0.59 * float(np.dot(l2, chord_template(spec)))\n',
    '        + 0.50 * coverage\n',
    '        + 0.10 * float(l1[spec.root])\n',
    '        - 0.22 * (1 - coverage)\n',
    '    )\n',
    '    if len(spec.intervals) >= 4:\n',
    '        score += 0.13 * float(l1[tones[-1]]) - 0.035\n',
    '    if spec.quality in {"aug", "dim", "sus2", "sus4", "add9", "power"}:\n',
    '        score -= 0.018\n',
    '    return score\n',
    '\n',
    '\n',
    'def _chord_transition_matrix(specs: Sequence[ChordSpec]) -> np.ndarray:\n',
    '    count = len(specs) + 1\n',
    '    transition = np.full((count, count), -0.43)\n',
    '    transition[0, 0] = 0.04\n',
    '    transition[0, 1:] = transition[1:, 0] = -0.16\n',
    '    for left_index, left in enumerate(specs, start=1):\n',
    '        for right_index, right in enumerate(specs, start=1):\n',
    '            if left_index == right_index:\n',
    '                score = 0.055\n',
    '            elif left.root == right.root:\n',
    '                score = -0.11\n',
    '            else:\n',
    '                distance = (right.root - left.root) % 12\n',
    '                score = (\n',
    '                    -0.16\n',
    '                    if distance in {5, 7}\n',
    '                    else -0.22\n',
    '                    if distance in {3, 4, 8, 9}\n',
    '                    else -0.28\n',
    '                    if distance in {2, 10}\n',
    '                    else -0.37\n',
    '                )\n',
    '            transition[left_index, right_index] = score\n',
    '    return transition\n',
    '\n',
    '\n',
    'def classify_chroma_segments(\n',
    '    vectors: np.ndarray,\n',
    '    energies: np.ndarray,\n',
    '    *,\n',
    '    bass_vectors: np.ndarray | None = None,\n',
    '    detail: str = "standard",\n',
    '    smoothing: float = 0.68,\n',
    '    local_keys: Sequence[tuple[int, str, float, str]] | None = None,\n',
    ') -> tuple[list[str], list[float], list[float], np.ndarray]:\n',
    '    matrix = np.asarray(vectors, dtype=float)\n',
    '    if matrix.ndim != 2 or matrix.shape[1] != 12:\n',
    '        raise ValueError("vectors must have shape (segments, 12)")\n',
    '    if len(matrix) == 0:\n',
    '        return [], [], [], np.asarray([], dtype=int)\n',
    '    energy = np.asarray(energies, dtype=float).reshape(-1)\n',
    '    bass = np.zeros_like(matrix) if bass_vectors is None else np.asarray(bass_vectors, dtype=float)\n',
    '    if len(energy) != len(matrix) or bass.shape != matrix.shape:\n',
    '        raise ValueError("feature arrays must have one row per segment")\n',
    '    specs = chord_vocabulary(detail)\n',
    '    emissions = np.zeros((len(matrix), len(specs) + 1))\n',
    '    tonalities: list[float] = []\n',
    '    positive = energy[energy > 1e-10]\n',
    '    median_energy = float(np.median(positive)) if positive.size else 1.0\n',
    '    for index, vector in enumerate(matrix):\n',
    '        entropy = _entropy(vector)\n',
    '        tonality = float(np.clip(1 - entropy, 0, 1))\n',
    '        tonalities.append(tonality)\n',
    '        relative_energy = float(energy[index] / (median_energy + 1e-12))\n',
    '        silence = float(np.clip((0.16 - relative_energy) / 0.16, 0, 1))\n',
    '        flatness = float(np.clip((entropy - 0.84) / 0.16, 0, 1))\n',
    '        emissions[index, 0] = 0.22 + 0.94 * silence + 0.34 * flatness\n',
    '        bass_mass = np.maximum(bass[index], 0)\n',
    '        bass_mass /= float(np.sum(bass_mass)) + 1e-12\n',
    '        local = local_keys[index] if local_keys and index < len(local_keys) else None\n',
    '        for state, spec in enumerate(specs, start=1):\n',
    '            tones = {(spec.root + interval) % 12 for interval in spec.intervals}\n',
    '            score = (\n',
    '                _chord_score(vector, spec)\n',
    '                + 0.18 * float(bass_mass[spec.root])\n',
    '                + 0.07 * float(np.sum(bass_mass[list(tones)]))\n',
    '            )\n',
    '            if local:\n',
    '                root, mode, confidence, _label = local\n',
    '                score += (0.07 if is_diatonic(spec, root, mode) else -0.018) * confidence\n',
    '            emissions[index, state] = score\n',
    '    transition = _chord_transition_matrix(specs) * (0.22 + 0.78 * float(np.clip(smoothing, 0, 1)))\n',
    '    dp = np.full_like(emissions, -np.inf)\n',
    '    back = np.zeros_like(emissions, dtype=np.int32)\n',
    '    dp[0] = emissions[0]\n',
    '    for index in range(1, len(matrix)):\n',
    '        options = dp[index - 1][:, None] + transition\n',
    '        back[index] = np.argmax(options, axis=0)\n',
    '        dp[index] = emissions[index] + np.max(options, axis=0)\n',
    '    states = np.zeros(len(matrix), dtype=np.int32)\n',
    '    states[-1] = int(np.argmax(dp[-1]))\n',
    '    for index in range(len(matrix) - 1, 0, -1):\n',
    '        states[index - 1] = back[index, states[index]]\n',
    '    labels: list[str] = []\n',
    '    confidences: list[float] = []\n',
    '    for index, state in enumerate(states):\n',
    '        local = local_keys[index] if local_keys else None\n',
    '        flats = key_prefers_flats(local[3]) if local else False\n',
    '        if state == 0:\n',
    '            label = "N"\n',
    '        else:\n',
], append=True)
