from __future__ import annotations

from pathlib import Path


def put(path: str, lines: list[str], *, append: bool = False) -> None:
    target = Path(path)
    target.parent.mkdir(parents=True, exist_ok=True)
    mode = "a" if append else "w"
    with target.open(mode, encoding="utf-8", newline="") as handle:
        handle.writelines(lines)


put('src/sgchords/models.py', [
    '        )\n',
], append=True)

put('src/sgchords/models.py', [
    '\n',
    '\n',
    '@dataclass(slots=True)\n',
    'class ChordSegment:\n',
    '    start: float\n',
    '    end: float\n',
    '    chord: str\n',
    '    confidence: float\n',
    '    local_key: str | None = None\n',
    '    bar: int | None = None\n',
    '    beat: float | None = None\n',
    '    bass: str | None = None\n',
    '\n',
    '    @property\n',
    '    def duration(self) -> float:\n',
    '        return max(0.0, self.end - self.start)\n',
    '\n',
    '    def to_row(self) -> list[Any]:\n',
    '        return [\n',
    '            round(self.start, 3),\n',
    '            round(self.end, 3),\n',
    '            self.chord,\n',
    '            round(self.confidence, 3),\n',
    '            self.local_key or "",\n',
    '            self.bar or "",\n',
    '            "" if self.beat is None else round(self.beat, 2),\n',
    '        ]\n',
    '\n',
    '    @classmethod\n',
    '    def from_dict(cls, value: dict[str, Any]) -> ChordSegment:\n',
    '        return cls(\n',
    '            start=float(value["start"]),\n',
    '            end=float(value["end"]),\n',
    '            chord=str(value["chord"]),\n',
    '            confidence=float(value.get("confidence", 0.0)),\n',
    '            local_key=(str(value["local_key"]) if value.get("local_key") else None),\n',
    '            bar=(int(value["bar"]) if value.get("bar") not in {None, ""} else None),\n',
    '            beat=(float(value["beat"]) if value.get("beat") not in {None, ""} else None),\n',
    '            bass=(str(value["bass"]) if value.get("bass") else None),\n',
    '        )\n',
    '\n',
    '\n',
    '@dataclass(slots=True)\n',
    'class AnalysisResult:\n',
    '    title: str\n',
    '    source: str\n',
    '    audio_path: str\n',
    '    duration: float\n',
    '    tempo_bpm: float | None\n',
    '    key: str\n',
    '    key_confidence: float\n',
    '    tuning_cents: float\n',
    '    segments: list[ChordSegment]\n',
    '    tempo_confidence: float = 0.0\n',
    '    meter: int = 4\n',
    '    meter_confidence: float = 0.0\n',
    '    beats: list[BeatPoint] = field(default_factory=list)\n',
    '    key_regions: list[KeyRegion] = field(default_factory=list)\n',
    '    patterns: list[ProgressionPattern] = field(default_factory=list)\n',
    '    drone: str | None = None\n',
    '    drone_confidence: float = 0.0\n',
    '    warnings: list[str] = field(default_factory=list)\n',
    '    used_beat_tracking: bool = True\n',
    '    analysis_version: str = "0.2"\n',
    '\n',
    '    def to_state(self) -> dict[str, Any]:\n',
    '        return asdict(self)\n',
    '\n',
    '    @classmethod\n',
    '    def from_state(cls, value: dict[str, Any]) -> AnalysisResult:\n',
    '        return cls(\n',
    '            title=str(value["title"]),\n',
    '            source=str(value["source"]),\n',
    '            audio_path=str(value["audio_path"]),\n',
    '            duration=float(value["duration"]),\n',
    '            tempo_bpm=(None if value.get("tempo_bpm") is None else float(value["tempo_bpm"])),\n',
    '            tempo_confidence=float(value.get("tempo_confidence", 0.0)),\n',
    '            meter=int(value.get("meter", 4)),\n',
    '            meter_confidence=float(value.get("meter_confidence", 0.0)),\n',
    '            key=str(value.get("key", "Unknown")),\n',
    '            key_confidence=float(value.get("key_confidence", 0.0)),\n',
    '            tuning_cents=float(value.get("tuning_cents", 0.0)),\n',
    '            segments=[ChordSegment.from_dict(item) for item in value.get("segments", [])],\n',
    '            beats=[BeatPoint.from_dict(item) for item in value.get("beats", [])],\n',
    '            key_regions=[KeyRegion.from_dict(item) for item in value.get("key_regions", [])],\n',
    '            patterns=[ProgressionPattern.from_dict(item) for item in value.get("patterns", [])],\n',
    '            drone=(str(value["drone"]) if value.get("drone") else None),\n',
    '            drone_confidence=float(value.get("drone_confidence", 0.0)),\n',
    '            warnings=[str(item) for item in value.get("warnings", [])],\n',
    '            used_beat_tracking=bool(value.get("used_beat_tracking", True)),\n',
    '            analysis_version=str(value.get("analysis_version", "0.1")),\n',
    '        )\n',
], append=True)

put('src/sgchords/service.py', [
    'from __future__ import annotations\n',
    '\n',
    'import os\n',
    'import shutil\n',
    'import tempfile\n',
    'import time\n',
    'import uuid\n',
    'from pathlib import Path\n',
    'from typing import Any\n',
    '\n',
    'from .analyzer import analyze_audio\n',
    'from .audio import InputError, is_youtube_url, prepare_local_audio, prepare_youtube_audio\n',
    'from .exports import rows_to_segments, write_exports\n',
    'from .models import AnalysisResult\n',
    '\n',
    'DEFAULT_MAX_DURATION_SECONDS = int(os.getenv("SGCHORDS_MAX_DURATION_SECONDS", "1200"))\n',
    'DEFAULT_JOB_TTL_SECONDS = int(os.getenv("SGCHORDS_JOB_TTL_SECONDS", "86400"))\n',
    '\n',
    '\n',
    'def default_workspace_root() -> Path:\n',
    '    configured = os.getenv("SGCHORDS_WORKSPACE")\n',
    '    return Path(configured).expanduser() if configured else Path(tempfile.gettempdir()) / "sgchords"\n',
    '\n',
    '\n',
    'def cleanup_old_jobs(root: str | Path, *, ttl_seconds: int = DEFAULT_JOB_TTL_SECONDS) -> None:\n',
    '    root = Path(root)\n',
    '    if not root.exists():\n',
    '        return\n',
    '    cutoff = time.time() - ttl_seconds\n',
    '    for path in root.iterdir():\n',
    '        try:\n',
    '            if path.is_dir() and path.stat().st_mtime < cutoff:\n',
    '                shutil.rmtree(path, ignore_errors=True)\n',
    '        except OSError:\n',
    '            continue\n',
    '\n',
    '\n',
    'def create_job_dir(root: str | Path | None = None) -> Path:\n',
    '    root_path = Path(root) if root is not None else default_workspace_root()\n',
    '    root_path.mkdir(parents=True, exist_ok=True)\n',
    '    cleanup_old_jobs(root_path)\n',
    '    job = root_path / uuid.uuid4().hex\n',
    '    job.mkdir(parents=True, exist_ok=False)\n',
    '    return job\n',
    '\n',
    '\n',
    'def analyze_request(\n',
    '    *,\n',
    '    youtube_url: str | None = None,\n',
    '    upload_path: str | Path | None = None,\n',
    '    detail: str = "standard",\n',
    '    smoothing: float = 0.68,\n',
    '    meter_override: int | None = None,\n',
    '    workspace_root: str | Path | None = None,\n',
    '    max_duration_seconds: int = DEFAULT_MAX_DURATION_SECONDS,\n',
    ') -> tuple[AnalysisResult, Path]:\n',
    '    url = (youtube_url or "").strip()\n',
    '    file_value = str(upload_path).strip() if upload_path else ""\n',
    '    if bool(url) == bool(file_value):\n',
    '        raise InputError("Provide exactly one source: a YouTube URL or an uploaded file.")\n',
    '    if url and not is_youtube_url(url):\n',
    '        raise InputError("Only full YouTube URLs are accepted in the URL field.")\n',
    '    job_dir = create_job_dir(workspace_root)\n',
    '    try:\n',
    '        prepared = (\n',
    '            prepare_youtube_audio(url, job_dir, max_duration_seconds=max_duration_seconds)\n',
    '            if url\n',
    '            else prepare_local_audio(file_value, job_dir, max_duration_seconds=max_duration_seconds)\n',
    '        )\n',
    '        analyzed = analyze_audio(\n',
    '            prepared.path,\n',
    '            detail=detail,\n',
    '            smoothing=smoothing,\n',
    '            meter_override=meter_override,\n',
    '        )\n',
    '        result = AnalysisResult(\n',
    '            title=prepared.title,\n',
    '            source=prepared.source,\n',
    '            audio_path=str(prepared.path),\n',
    '            duration=analyzed.duration,\n',
    '            tempo_bpm=analyzed.tempo_bpm,\n',
    '            tempo_confidence=analyzed.tempo_confidence,\n',
    '            meter=analyzed.meter,\n',
    '            meter_confidence=analyzed.meter_confidence,\n',
    '            key=analyzed.key,\n',
    '            key_confidence=analyzed.key_confidence,\n',
    '            tuning_cents=analyzed.tuning_cents,\n',
    '            segments=analyzed.segments,\n',
    '            beats=analyzed.beats,\n',
    '            key_regions=analyzed.key_regions,\n',
    '            patterns=analyzed.patterns,\n',
    '            drone=analyzed.drone,\n',
    '            drone_confidence=analyzed.drone_confidence,\n',
    '            warnings=analyzed.warnings,\n',
    '            used_beat_tracking=analyzed.used_beat_tracking,\n',
    '        )\n',
    '        return result, job_dir\n',
    '    except Exception:\n',
    '        shutil.rmtree(job_dir, ignore_errors=True)\n',
    '        raise\n',
    '\n',
    '\n',
    'def export_from_state(\n',
    '    state: dict[str, Any],\n',
    '    timeline: Any,\n',
    '    *,\n',
    '    transpose: int = 0,\n',
    '    instrument: str = "guitar",\n',
    '    capo: int = 0,\n',
    '    notation: str = "standard",\n',
    '    meter_override: int | None = None,\n',
    ') -> tuple[AnalysisResult, list[str]]:\n',
    '    if not state:\n',
    '        raise InputError("Analyze a song before exporting.")\n',
    '    result = AnalysisResult.from_state(state)\n',
    '    segments = rows_to_segments(timeline)\n',
    '    if not segments:\n',
    '        raise InputError("The timeline is empty.")\n',
    '    files = write_exports(\n',
    '        result,\n',
    '        Path(result.audio_path).parent / "exports",\n',
    '        segments=segments,\n',
    '        transpose=int(transpose),\n',
    '        instrument=instrument,\n',
    '        capo=int(capo),\n',
    '        notation=notation,\n',
    '        meter_override=meter_override,\n',
    '    )\n',
    '    return result, files\n',
], append=False)

put('src/sgchords/ui.py', [
    'from __future__ import annotations\n',
    '\n',
    'import os\n',
    'from pathlib import Path\n',
    'from typing import Any\n',
    '\n',
    'import gradio as gr\n',
    'import pandas as pd\n',
    '\n',
    'from .chords import (\n',
    '    format_chord_notation,\n',
    '    key_prefers_flats,\n',
    '    render_chord_diagrams_html,\n',
    '    suggest_capo,\n',
    '    transpose_key,\n',
    ')\n',
    'from .exports import (\n',
    '    capo_shape_segments,\n',
    '    merge_adjacent_segments,\n',
    '    quantize_segments,\n',
    '    render_bar_chart,\n',
    '    render_summary,\n',
    '    rows_to_segments,\n',
    '    transpose_segments,\n',
    '    write_exports,\n',
    ')\n',
    'from .models import AnalysisResult, ChordSegment\n',
    'from .service import analyze_request, default_workspace_root, export_from_state\n',
    '\n',
    'HEADERS = ["Start (s)", "End (s)", "Chord", "Confidence", "Local key", "Bar", "Beat"]\n',
    'APP_CSS = """\n',
    ':root { --sg-accent:#6574ff; --sg-accent2:#a25cff; }\n',
    '.gradio-container { max-width: 1480px !important; }\n',
    '.sg-hero { padding:28px; border-radius:24px; margin-bottom:16px; border:1px solid var(--border-color-primary); background:linear-gradient(135deg,rgba(101,116,255,.18),rgba(162,92,255,.11)); }\n',
    '.sg-hero h1 { margin:0 0 8px; font-size:clamp(2.2rem,5vw,3.8rem); letter-spacing:-.05em; }\n',
    '.sg-hero p { margin:0; max-width:78ch; font-size:1.03rem; opacity:.84; }\n',
    '.sg-card { border:1px solid var(--border-color-primary)!important; border-radius:20px!important; padding:4px!important; }\n',
    '.sg-note { opacity:.8; max-width:90rem; }\n',
    '.sg-output textarea { font-family:ui-monospace,SFMono-Regular,Menlo,monospace!important; }\n',
    '.sg-diagram-grid { display:grid; grid-template-columns:repeat(auto-fill,minmax(130px,1fr)); gap:12px; }\n',
    '.sg-diagram-card { border:1px solid var(--border-color-primary); border-radius:16px; padding:8px; background:var(--block-background-fill); }\n',
    '.sg-diagram-card svg { width:100%; height:auto; stroke:currentColor; fill:none; }\n',
    '.sg-diagram-title { fill:currentColor; stroke:none; font:700 14px ui-sans-serif,system-ui; }\n',
    '.sg-fret-label,.sg-marker { fill:currentColor; stroke:none; font:600 10px ui-sans-serif,system-ui; }\n',
    '.sg-open { stroke:currentColor; stroke-width:1.5; }\n',
    '.sg-finger { fill:currentColor; stroke:currentColor; }\n',
    '.sg-missing-shapes { grid-column:1/-1; opacity:.7; padding:8px; }\n',
    '"""\n',
    'PROGRESS = gr.Progress()\n',
    '\n',
    '\n',
    'class SyncedChordViewer(gr.HTML):\n',
    '    """A browser-side chord follower synchronized to the Gradio audio element."""\n',
    '\n',
    '    def __init__(self, value: dict[str, Any] | None = None, **kwargs: Any) -> None:\n',
    '        html_template = r"""\n',
    '        <div class="sg-sync-shell">\n',
    '          <div class="sg-now">\n',
    '            <div><span class="sg-kicker">CURRENT</span><div class="sg-current" data-role="current">—</div><div class="sg-meta" data-role="meta">Analyze a song to begin.</div></div>\n',
    '            <div class="sg-next-wrap"><span class="sg-kicker">NEXT</span><div class="sg-next" data-role="next">—</div><div class="sg-countdown" data-role="countdown">—</div></div>\n',
    '          </div>\n',
    '          <div class="sg-actions">\n',
    '            <button type="button" data-action="back">−5s</button>\n',
], append=False)
