from __future__ import annotations

from pathlib import Path


def put(path: str, lines: list[str], *, append: bool = False) -> None:
    target = Path(path)
    target.parent.mkdir(parents=True, exist_ok=True)
    mode = "a" if append else "w"
    with target.open(mode, encoding="utf-8", newline="") as handle:
        handle.writelines(lines)


put('tests/test_analyzer.py', [
    '        if segment.start <= timestamp < segment.end:\n',
], append=True)

put('tests/test_analyzer.py', [
    '            return simplify_chord(segment.chord)\n',
    '    return "N"\n',
    '\n',
    '\n',
    'def test_analyze_synthetic_progression_and_boundaries(tmp_path: Path) -> None:\n',
    '    path = tmp_path / "known.wav"\n',
    '    sf.write(path, make_progression(), 22_050)\n',
    '    output = analyze_audio(\n',
    '        path,\n',
    '        detail="standard",\n',
    '        smoothing=0.5,\n',
    '        config=AnalyzerConfig(local_key_window_seconds=6, local_key_min_region_seconds=3),\n',
    '    )\n',
    '    assert [chord_at(output.segments, time) for time in (1, 3, 5, 7)] == ["C", "G", "Am", "F"]\n',
    '    boundaries = [segment.start for segment in output.segments[1:]]\n',
    '    for expected in (2, 4, 6):\n',
    '        assert min(abs(actual - expected) for actual in boundaries) < 0.5\n',
    '    assert output.beats\n',
    '    assert output.key_regions\n',
    '\n',
    '\n',
    'def test_silence_rejected(tmp_path: Path) -> None:\n',
    '    path = tmp_path / "silent.wav"\n',
    '    sf.write(path, np.zeros(22_050 * 3), 22_050)\n',
    '    with pytest.raises(AnalysisError, match="silent"):\n',
    '        analyze_audio(path)\n',
], append=True)

put('tests/test_audio.py', [
    'from sgchords.audio import is_youtube_url\n',
    '\n',
    '\n',
    'def test_url_validation() -> None:\n',
    '    assert is_youtube_url("https://youtu.be/abc")\n',
    '    assert is_youtube_url("https://www.youtube.com/watch?v=abc")\n',
    '    assert not is_youtube_url("https://example.com/video")\n',
], append=False)

put('tests/test_chords.py', [
    'from __future__ import annotations\n',
    '\n',
    'import numpy as np\n',
    '\n',
    'from sgchords.analyzer import classify_chroma_segments, detect_drone, estimate_local_keys\n',
    'from sgchords.chords import (\n',
    '    estimate_key,\n',
    '    nashville_number,\n',
    '    roman_numeral,\n',
    '    simplify_chord,\n',
    '    transpose_chord,\n',
    '    transpose_key,\n',
    ')\n',
    '\n',
    '\n',
    'def chord_vector(root: int, intervals: tuple[int, ...], *, drone: int | None = None) -> np.ndarray:\n',
    '    vector = np.full(12, 0.005)\n',
    '    for interval, weight in zip(intervals, (1.0, 0.82, 0.68, 0.54), strict=False):\n',
    '        vector[(root + interval) % 12] += weight\n',
    '    if drone is not None:\n',
    '        vector[drone] += 0.70\n',
    '    return vector\n',
    '\n',
    '\n',
    'def test_transpose_and_number_notation_preserve_slash_bass() -> None:\n',
    '    assert transpose_chord("C#m7/G#", 2) == "D#m7/A#"\n',
    '    assert transpose_chord("Bb/F", 2, prefer_flats=True) == "C/G"\n',
    '    assert simplify_chord("F#maj7/C#", keep_bass=True) == "F#/C#"\n',
    '    assert transpose_key("D dorian", 2) == "E dorian"\n',
    '    assert roman_numeral("Dm/F", "C major") == "ii/IV"\n',
    '    assert nashville_number("G7/B", "C major") == "57/7"\n',
    '\n',
    '\n',
    'def test_modal_key_estimation_can_recognize_d_dorian() -> None:\n',
    '    profile = (\n',
    '        chord_vector(2, (0, 3, 7)) * 4 + chord_vector(7, (0, 4, 7)) * 3 + chord_vector(0, (0, 4, 7))\n',
    '    )\n',
    '    key, confidence, root, mode = estimate_key(profile)\n',
    '    assert (root, mode, key) == (2, "dorian", "D dorian")\n',
    '    assert confidence > 0\n',
    '\n',
    '\n',
    'def test_local_key_tracker_finds_modulation() -> None:\n',
    '    c = [\n',
    '        chord_vector(0, (0, 4, 7)),\n',
    '        chord_vector(5, (0, 4, 7)),\n',
    '        chord_vector(7, (0, 4, 7)),\n',
    '        chord_vector(9, (0, 3, 7)),\n',
    '    ]\n',
    '    d = [\n',
    '        chord_vector(2, (0, 4, 7)),\n',
    '        chord_vector(7, (0, 4, 7)),\n',
    '        chord_vector(9, (0, 4, 7)),\n',
    '        chord_vector(11, (0, 3, 7)),\n',
    '    ]\n',
    '    vectors = np.asarray(c * 4 + d * 4)\n',
    '    boundaries = np.arange(len(vectors) + 1, dtype=float) * 2\n',
    '    local, regions, dominant, confidence = estimate_local_keys(\n',
    '        vectors, np.ones(len(vectors)), boundaries, window_seconds=8, min_region_seconds=5\n',
    '    )\n',
    '    labels = [item[3] for item in local]\n',
    '    assert "C major" in labels[: len(labels) // 2]\n',
    '    assert "D major" in labels[len(labels) // 2 :]\n',
    '    assert len(regions) >= 2\n',
    '    assert dominant in {"C major", "D major"}\n',
    '    assert confidence >= 0\n',
    '\n',
    '\n',
    'def test_drone_detection_reduces_constant_pitch_bias() -> None:\n',
    '    vectors = np.asarray(\n',
    '        [\n',
    '            chord_vector(2, (0, 3, 7), drone=2),\n',
    '            chord_vector(7, (0, 4, 7), drone=2),\n',
    '            chord_vector(0, (0, 4, 7), drone=2),\n',
    '            chord_vector(9, (0, 3, 7), drone=2),\n',
    '        ]\n',
    '        * 4\n',
    '    )\n',
    '    root, confidence, corrected = detect_drone(vectors, np.ones(len(vectors)))\n',
    '    assert root == 2\n',
    '    assert confidence >= 0.38\n',
    '    assert np.median(corrected[:, 2]) < np.median(vectors[:, 2])\n',
    '\n',
    '\n',
    'def test_classifier_decodes_progression_and_inversion() -> None:\n',
    '    vectors = np.asarray(\n',
    '        [\n',
    '            chord_vector(0, (0, 4, 7)),\n',
    '            chord_vector(7, (0, 4, 7)),\n',
    '            chord_vector(9, (0, 3, 7)),\n',
    '            chord_vector(5, (0, 4, 7)),\n',
    '        ]\n',
    '    )\n',
    '    bass = np.zeros_like(vectors)\n',
    '    bass[0, 0] = 1\n',
    '    bass[1, 11] = 1\n',
    '    bass[2, 9] = 1\n',
    '    bass[3, 5] = 1\n',
    '    labels, confidence, _tonality, _states = classify_chroma_segments(\n',
    '        vectors,\n',
    '        np.ones(4),\n',
    '        bass_vectors=bass,\n',
    '        detail="standard",\n',
    '        smoothing=0.2,\n',
    '        local_keys=[(0, "major", 0.9, "C major")] * 4,\n',
    '    )\n',
    '    assert labels == ["C", "G/B", "Am", "F"]\n',
    '    assert min(confidence) > 0.35\n',
], append=False)

put('tests/test_cli.py', [
    'from sgchords.cli import build_parser\n',
    '\n',
    '\n',
    'def test_cli_options() -> None:\n',
    '    args = build_parser().parse_args(\n',
    '        [\n',
    '            "song.wav",\n',
    '            "--detail",\n',
    '            "detailed",\n',
    '            "--meter",\n',
    '            "6",\n',
    '            "--transpose",\n',
    '            "2",\n',
    '            "--capo",\n',
    '            "3",\n',
    '            "--notation",\n',
    '            "nashville",\n',
    '            "--instrument",\n',
    '            "ukulele",\n',
    '        ]\n',
    '    )\n',
    '    assert (args.detail, args.meter, args.transpose, args.capo, args.notation, args.instrument) == (\n',
    '        "detailed",\n',
    '        "6",\n',
    '        2,\n',
    '        "3",\n',
    '        "nashville",\n',
    '        "ukulele",\n',
    '    )\n',
], append=False)

put('tests/test_exports.py', [
    'from __future__ import annotations\n',
    '\n',
    'import json\n',
    'from pathlib import Path\n',
    '\n',
    'import pandas as pd\n',
    '\n',
    'from sgchords.chords import render_chord_diagrams_html\n',
    'from sgchords.exports import quantize_segments, render_bar_chart, rows_to_segments, write_exports\n',
    'from sgchords.models import AnalysisResult, BeatPoint, ChordSegment, KeyRegion, ProgressionPattern\n',
    '\n',
    '\n',
    'def make_result(tmp_path: Path) -> AnalysisResult:\n',
    '    beats = [\n',
    '        BeatPoint(float(index), index, index // 4 + 1, index % 4 + 1, 0.8, index % 4 == 0)\n',
    '        for index in range(9)\n',
    '    ]\n',
    '    return AnalysisResult(\n',
    '        title="Known Progression",\n',
    '        source="test.wav",\n',
    '        audio_path=str(tmp_path / "source.wav"),\n',
    '        duration=8,\n',
    '        tempo_bpm=60,\n',
    '        tempo_confidence=0.9,\n',
    '        meter=4,\n',
    '        meter_confidence=0.8,\n',
    '        key="C major",\n',
    '        key_confidence=0.75,\n',
    '        tuning_cents=2,\n',
    '        segments=[\n',
    '            ChordSegment(0, 2, "C", 0.9, "C major", 1, 1),\n',
    '            ChordSegment(2, 4, "G/B", 0.8, "C major", 1, 3),\n',
    '            ChordSegment(4, 6, "Am", 0.85, "C major", 2, 1),\n',
    '            ChordSegment(6, 8, "F", 0.8, "C major", 2, 3),\n',
    '        ],\n',
    '        beats=beats,\n',
    '        key_regions=[KeyRegion(0, 8, "C major", 0.75, 0, "major")],\n',
    '        patterns=[ProgressionPattern(["C", "G/B", "Am", "F"], 2, 1, 1)],\n',
    '    )\n',
    '\n',
    '\n',
    'def test_rows_quantize_and_bar_chart(tmp_path: Path) -> None:\n',
    '    result = make_result(tmp_path)\n',
    '    frame = pd.DataFrame(\n',
    '        [[0.08, 2.12, "C", 0.8, "C major", 1, 1], [2.12, 4.04, "G", 0.7, "C major", 1, 3]],\n',
    '        columns=["Start (s)", "End (s)", "Chord", "Confidence", "Local key", "Bar", "Beat"],\n',
    '    )\n',
    '    snapped = quantize_segments(rows_to_segments(frame), result.beats, duration=4)\n',
    '    assert (snapped[0].start, snapped[0].end, snapped[-1].end) == (0, 2, 4)\n',
    '    chart = render_bar_chart(result, result.segments, capo=2)\n',
    '    assert "Capo 2" in chart and "Bb" in chart\n',
    '    assert "vi" in render_bar_chart(result, result.segments, notation="roman")\n',
    '    assert "6m" in render_bar_chart(result, result.segments, notation="nashville")\n',
    '\n',
    '\n',
    'def test_diagrams_and_exports(tmp_path: Path) -> None:\n',
    '    assert render_chord_diagrams_html(["C", "Am", "G7"], "guitar").count("<svg") == 3\n',
    '    result = make_result(tmp_path)\n',
    '    files = write_exports(\n',
    '        result, tmp_path / "exports", transpose=2, capo=2, notation="roman", instrument="ukulele"\n',
    '    )\n',
    '    assert len(files) == 7 and all(Path(path).is_file() for path in files)\n',
    '    payload = json.loads((tmp_path / "exports" / "known-progression-analysis.json").read_text())\n',
    '    assert payload["key"] == "D major" and payload["capo"] == 2 and payload["beats"]\n',
    '    assert (tmp_path / "exports" / "known-progression.srt").read_text().startswith("1\\n")\n',
], append=False)

put('tests/test_ui.py', [
    'from sgchords.ui import SyncedChordViewer, build_demo\n',
    '\n',
    '\n',
    'def test_synced_viewer_and_ui_build() -> None:\n',
    '    viewer = SyncedChordViewer(\n',
    '        value={\n',
    '            "segments": [\n',
    '                {\n',
    '                    "start": 0,\n',
    '                    "end": 2,\n',
    '                    "time": "00:00.0",\n',
    '                    "display": "C",\n',
    '                    "secondary": "bar 1",\n',
    '                    "confidence": 0.9,\n',
    '                }\n',
    '            ]\n',
    '        }\n',
    '    )\n',
    '    assert viewer is not None\n',
    '    assert build_demo() is not None\n',
], append=False)
