from __future__ import annotations

from pathlib import Path


def put(path: str, lines: list[str], *, append: bool = False) -> None:
    target = Path(path)
    target.parent.mkdir(parents=True, exist_ok=True)
    mode = "a" if append else "w"
    with target.open(mode, encoding="utf-8", newline="") as handle:
        handle.writelines(lines)


put('src/sgchords/analyzer.py', [
    'def _load_audio(path: str | Path, target_rate: int) -> tuple[np.ndarray, int]:\n',
], append=True)

put('src/sgchords/analyzer.py', [
    '    try:\n',
    '        y, sample_rate = sf.read(str(path), dtype="float32", always_2d=False)\n',
    '    except Exception as exc:\n',
    '        raise AnalysisError(f"Could not decode the normalized audio: {exc}") from exc\n',
    '    if y.ndim > 1:\n',
    '        y = np.mean(y, axis=1, dtype=np.float32)\n',
    '    y = np.nan_to_num(np.asarray(y, dtype=np.float32).reshape(-1))\n',
    '    if sample_rate != target_rate and y.size:\n',
    '        divisor = gcd(int(sample_rate), int(target_rate))\n',
    '        y = signal.resample_poly(y, target_rate // divisor, sample_rate // divisor).astype(\n',
    '            np.float32\n',
    '        )\n',
    '        sample_rate = target_rate\n',
    '    return y, int(sample_rate)\n',
    '\n',
    '\n',
    'def _estimate_beats(\n',
    '    onset: np.ndarray,\n',
    '    *,\n',
    '    sample_rate: int,\n',
    '    hop_length: int,\n',
    ') -> tuple[float | None, np.ndarray, float]:\n',
    '    envelope = np.nan_to_num(np.asarray(onset, dtype=float).reshape(-1))\n',
    '    if envelope.size < 8 or float(np.max(envelope)) <= 1e-8:\n',
    '        return None, np.asarray([], dtype=int), 0.0\n',
    '    try:\n',
    '        tempo_raw, beat_frames = librosa.beat.beat_track(\n',
    '            onset_envelope=envelope,\n',
    '            sr=sample_rate,\n',
    '            hop_length=hop_length,\n',
    '            trim=False,\n',
    '            units="frames",\n',
    '            sparse=True,\n',
    '        )\n',
    '        tempo = float(np.atleast_1d(tempo_raw)[0])\n',
    '        beats = np.asarray(beat_frames, dtype=int)\n',
    '    except Exception:\n',
    '        tempo, beats = 0.0, np.asarray([], dtype=int)\n',
    '    beats = beats[(beats >= 0) & (beats < envelope.size)]\n',
    '    if beats.size < 3 or not 35 <= tempo <= 260:\n',
    '        # Autocorrelation fallback: less expressive than the dynamic-programming tracker,\n',
    '        # but it preserves a usable practice grid for sparse folk recordings and click-light audio.\n',
    '        centered = np.maximum(envelope - np.median(envelope), 0.0)\n',
    '        centered = np.convolve(centered, np.asarray([0.2, 0.6, 0.2]), mode="same")\n',
    '        if float(np.max(centered)) <= 1e-8:\n',
    '            return None, np.asarray([], dtype=int), 0.0\n',
    '        centered /= float(np.max(centered)) + 1e-12\n',
    '        min_lag = max(1, int(round(60 * sample_rate / (hop_length * 220))))\n',
    '        max_lag = min(len(centered) - 1, int(round(60 * sample_rate / (hop_length * 45))))\n',
    '        autocorrelation = signal.fftconvolve(centered, centered[::-1], mode="full")[\n',
    '            len(centered) - 1 :\n',
    '        ]\n',
    '        lags = np.arange(min_lag, max_lag + 1)\n',
    '        bpms = 60 * sample_rate / (hop_length * lags)\n',
    '        preference = np.exp(-0.5 * (np.log2(bpms / 100.0) / 0.85) ** 2)\n',
    '        scores = autocorrelation[lags] * preference\n',
    '        if scores.size == 0 or float(np.max(scores)) <= 1e-8:\n',
    '            return None, np.asarray([], dtype=int), 0.0\n',
    '        lag = int(lags[int(np.argmax(scores))])\n',
    '        phase_scores = np.asarray([np.sum(centered[phase::lag]) for phase in range(lag)])\n',
    '        phase = int(np.argmax(phase_scores))\n',
    '        nominal = np.arange(phase, len(centered), lag, dtype=int)\n',
    '        radius = max(1, int(round(lag * 0.22)))\n',
    '        refined = []\n',
    '        for frame in nominal:\n',
    '            left = max(0, frame - radius)\n',
    '            right = min(len(centered), frame + radius + 1)\n',
    '            refined.append(left + int(np.argmax(centered[left:right])))\n',
    '        beats = np.asarray(sorted(set(refined)), dtype=int)\n',
    '        tempo = float(60 * sample_rate / (hop_length * lag))\n',
    '        if beats.size < 3:\n',
    '            return None, np.asarray([], dtype=int), 0.0\n',
    '        peak_ratio = float(np.max(scores) / (autocorrelation[0] + 1e-12))\n',
    '        fallback_confidence = float(np.clip(0.20 + 0.80 * peak_ratio, 0.0, 0.62))\n',
    '    else:\n',
    '        fallback_confidence = 0.0\n',
    '\n',
    '    gaps = np.diff(beats)\n',
    '    median_gap = float(np.median(gaps)) if gaps.size else 0.0\n',
    '    regularity = (\n',
    '        float(np.mean(np.abs(gaps - median_gap) <= max(2.0, median_gap * 0.25)))\n',
    '        if median_gap\n',
    '        else 0.0\n',
    '    )\n',
    '    normalized = envelope / (float(np.max(envelope)) + 1e-12)\n',
    '    beat_salience = float(np.mean(normalized[beats]))\n',
    '    confidence = float(np.clip(0.55 * regularity + 0.45 * beat_salience, 0.0, 1.0))\n',
    '    if fallback_confidence:\n',
    '        confidence = min(confidence, fallback_confidence)\n',
    '    return tempo, beats, confidence\n',
    '\n',
    '\n',
    'def _estimate_meter(\n',
    '    strengths: np.ndarray, meter_override: int | None = None\n',
    ') -> tuple[int, int, float]:\n',
    '    if meter_override in {3, 4, 6}:\n',
    '        return int(meter_override), 0, 1.0\n',
    '    values = np.nan_to_num(np.asarray(strengths, dtype=float).reshape(-1))\n',
    '    if values.size < 8:\n',
    '        return 4, 0, 0.0\n',
    '    values = values / (float(np.max(values)) + 1e-12)\n',
    '    candidates: list[tuple[float, int, int]] = []\n',
    '    for meter in (3, 4, 6):\n',
    '        if values.size < meter * 2:\n',
    '            continue\n',
    '        for phase in range(meter):\n',
    '            down = values[phase::meter]\n',
    '            other_mask = np.ones(values.size, dtype=bool)\n',
    '            other_mask[phase::meter] = False\n',
    '            others = values[other_mask]\n',
    '            accent = float(np.mean(down) - np.mean(others))\n',
    '            consistency = 1.0 - float(np.std(down))\n',
    '            score = 0.72 * accent + 0.28 * consistency\n',
    '            # Slight 4/4 prior prevents arbitrary 6/8 labels when accents are flat.\n',
    '            if meter == 4:\n',
    '                score += 0.025\n',
    '            candidates.append((score, meter, phase))\n',
    '    candidates.sort(reverse=True)\n',
    '    if not candidates:\n',
    '        return 4, 0, 0.0\n',
    '    best = candidates[0]\n',
    '    second = candidates[1] if len(candidates) > 1 else (best[0], 4, 0)\n',
    '    confidence = float(np.clip((best[0] - second[0]) / 0.16 + 0.18, 0.0, 1.0))\n',
    '    return best[1], best[2], confidence\n',
    '\n',
    '\n',
    'def _harmonic_novelty(chroma: np.ndarray, onset: np.ndarray) -> np.ndarray:\n',
    '    normalized = chroma / np.maximum(np.linalg.norm(chroma, axis=0, keepdims=True), 1e-12)\n',
    '    change = np.zeros(normalized.shape[1], dtype=float)\n',
    '    if normalized.shape[1] > 1:\n',
    '        change[1:] = 1.0 - np.sum(normalized[:, 1:] * normalized[:, :-1], axis=0)\n',
    '    onset_values = np.asarray(onset, dtype=float)[: len(change)]\n',
    '    onset_values = onset_values / (float(np.max(onset_values)) + 1e-12)\n',
    '    change = change / (float(np.max(change)) + 1e-12)\n',
    '    return np.nan_to_num(0.72 * change + 0.28 * onset_values)\n',
    '\n',
    '\n',
    'def _refine_beat_frames(\n',
    '    beats: np.ndarray,\n',
    '    novelty: np.ndarray,\n',
    '    ratio: float,\n',
    ') -> np.ndarray:\n',
    '    if beats.size < 3:\n',
    '        return beats\n',
    '    median_gap = max(2, int(round(float(np.median(np.diff(beats))))))\n',
    '    radius = max(1, int(round(median_gap * ratio))\n',
    '    refined: list[int] = []\n',
    '    for beat in beats:\n',
    '        left = max(0, int(beat) - radius)\n',
    '        right = min(len(novelty), int(beat) + radius + 1)\n',
    '        refined.append(left + int(np.argmax(novelty[left:right])) if right > left else int(beat))\n',
    '    return np.asarray(sorted(set(refined)), dtype=int)\n',
    '\n',
    '\n',
    'def _fill_large_gaps(boundaries: list[float], max_gap: float) -> list[float]:\n',
    '    result = [boundaries[0]]\n',
    '    for end in boundaries[1:]:\n',
    '        start = result[-1]\n',
    '        gap = end - start\n',
    '        if gap > max_gap:\n',
    '            pieces = int(np.ceil(gap / max_gap))\n',
    '            result.extend(start + gap * index / pieces for index in range(1, pieces))\n',
    '        result.append(end)\n',
    '    return result\n',
    '\n',
    '\n',
    'def _segment_boundaries(\n',
    '    duration: float,\n',
    '    beat_times: np.ndarray,\n',
    '    config: AnalyzerConfig,\n',
    ') -> tuple[np.ndarray, bool]:\n',
    '    valid = sorted(\n',
    '        {\n',
    '            float(value)\n',
    '            for value in beat_times\n',
    '            if config.min_segment_seconds < value < duration - config.min_segment_seconds\n',
    '        }\n',
    '    )\n',
    '    used_beats = len(valid) >= 3\n',
    '    if used_beats:\n',
    '        raw = [0.0, *valid, duration]\n',
    '    else:\n',
    '        raw = list(np.arange(0.0, duration, config.fallback_window_seconds)) + [duration]\n',
    '    filled = _fill_large_gaps(raw, config.max_segment_seconds)\n',
    '    filtered = [filled[0]]\n',
    '    for value in filled[1:]:\n',
    '        if value == duration or value - filtered[-1] >= config.min_segment_seconds:\n',
    '            filtered.append(value)\n',
    '    if filtered[-1] != duration:\n',
    '        filtered.append(duration)\n',
    '    return np.asarray(filtered), used_beats\n',
    '\n',
    '\n',
    'def _lowpass(y: np.ndarray, sample_rate: int, cutoff_hz: float = 330.0) -> np.ndarray:\n',
    '    sos = signal.butter(4, cutoff_hz, btype="lowpass", fs=sample_rate, output="sos")\n',
    '    return signal.sosfiltfilt(sos, y).astype(np.float32, copy=False)\n',
    '\n',
    '\n',
    'def _aggregate_features(\n',
    '    chroma: np.ndarray,\n',
    '    bass_chroma: np.ndarray,\n',
    '    rms: np.ndarray,\n',
    '    boundaries: np.ndarray,\n',
    '    *,\n',
    '    sample_rate: int,\n',
    '    hop_length: int,\n',
    ') -> tuple[np.ndarray, np.ndarray, np.ndarray]:\n',
    '    count = min(chroma.shape[1], bass_chroma.shape[1], rms.shape[0])\n',
    '    chroma, bass_chroma, rms = chroma[:, :count], bass_chroma[:, :count], rms[:count]\n',
    '    times = librosa.frames_to_time(np.arange(count), sr=sample_rate, hop_length=hop_length)\n',
    '    vectors: list[np.ndarray] = []\n',
    '    bass_vectors: list[np.ndarray] = []\n',
    '    energies: list[float] = []\n',
    '    for start, end in zip(boundaries[:-1], boundaries[1:], strict=True):\n',
    '        left = min(int(np.searchsorted(times, start, side="left")), count - 1)\n',
    '        right = min(max(int(np.searchsorted(times, end, side="right")), left + 1), count)\n',
    '        local_rms = rms[left:right]\n',
    '        weights = local_rms + max(float(np.max(local_rms)), 1e-8) * 0.06\n',
    '        harmonic_window = chroma[:, left:right]\n',
    '        bass_window = bass_chroma[:, left:right]\n',
    '        vector = 0.58 * np.median(harmonic_window, axis=1) + 0.42 * np.average(\n',
    '            harmonic_window, axis=1, weights=weights\n',
    '        )\n',
    '        bass = 0.48 * np.median(bass_window, axis=1) + 0.52 * np.average(\n',
    '            bass_window, axis=1, weights=weights\n',
    '        )\n',
    '        vectors.append(np.nan_to_num(vector))\n',
    '        bass_vectors.append(np.nan_to_num(bass))\n',
    '        energies.append(float(np.median(local_rms)))\n',
    '    return np.asarray(vectors), np.asarray(bass_vectors), np.asarray(energies)\n',
    '\n',
    '\n',
    'def _entropy(vector: np.ndarray) -> float:\n',
    '    values = np.maximum(np.asarray(vector, dtype=float), 0.0)\n',
    '    probabilities = values / (float(np.sum(values)) + 1e-12)\n',
    '    nonzero = probabilities[probabilities > 1e-12]\n',
    '    return float(-np.sum(nonzero * np.log(nonzero)) / np.log(12.0)) if nonzero.size else 1.0\n',
    '\n',
    '\n',
    'def detect_drone(vectors: np.ndarray, energies: np.ndarray) -> tuple[int | None, float, np.ndarray]:\n',
    '    matrix = np.maximum(np.asarray(vectors, dtype=float), 0.0)\n',
    '    if matrix.ndim != 2 or matrix.shape[0] < 6:\n',
    '        return None, 0.0, matrix\n',
    '    energy = np.asarray(energies, dtype=float)\n',
    '    active = energy >= max(float(np.median(energy)) * 0.16, 1e-8)\n',
    '    if np.count_nonzero(active) < 5:\n',
    '        active = np.ones(matrix.shape[0], dtype=bool)\n',
    '    mass = matrix / np.maximum(np.sum(matrix, axis=1, keepdims=True), 1e-12)\n',
    '    profile = np.percentile(mass[active], 30, axis=0)\n',
    '    order = np.argsort(profile)[::-1]\n',
    '    root = int(order[0])\n',
    '    top, second = float(profile[order[0]]), float(profile[order[1]]) + 1e-12\n',
    '    prevalence = float(np.mean(mass[active, root] >= max(0.10, top * 0.72)))\n',
    '    dominance = top / second\n',
    '    confidence = float(\n',
    '        np.clip(0.55 * (prevalence - 0.48) / 0.48 + 0.45 * (dominance - 1.03) / 1.15, 0.0, 1.0)\n',
    '    )\n',
    '    if confidence < 0.38 or top < 0.085:\n',
    '        return None, confidence, matrix\n',
    '    corrected = mass.copy()\n',
], append=True)
