from __future__ import annotations

from pathlib import Path


def put(path: str, lines: list[str], *, append: bool = False) -> None:
    target = Path(path)
    target.parent.mkdir(parents=True, exist_ok=True)
    mode = "a" if append else "w"
    with target.open(mode, encoding="utf-8", newline="") as handle:
        handle.writelines(lines)


put('src/sgchords/analyzer.py', [
    '                local_keys[index][3] if local_keys else None,\n',
], append=True)

put('src/sgchords/analyzer.py', [
    '                bar,\n',
    '                beat,\n',
    '                parsed_bass,\n',
    '            )\n',
    '        )\n',
    '    segments = _merge_segments(raw_segments)\n',
    '    patterns = detect_progression_patterns(segments, beats, meter)\n',
    '    sounding = [segment for segment in segments if segment.chord != "N"]\n',
    '    mean_confidence = (\n',
    '        float(\n',
    '            np.average(\n',
    '                [item.confidence for item in sounding], weights=[item.duration for item in sounding]\n',
    '            )\n',
    '        )\n',
    '        if sounding\n',
    '        else 0.0\n',
    '    )\n',
    '    mean_tonality = float(np.mean(tonalities)) if tonalities else 0.0\n',
    '    parsed_dominant = next(\n',
    '        ((region.root, region.mode) for region in key_regions if region.key == dominant_key),\n',
    '        (0, "major"),\n',
    '    )\n',
    '    ratio = _diatonic_duration_ratio(sounding, *parsed_dominant, detail)\n',
    '    if not sounding:\n',
    '        warnings.append(\n',
    '            "No stable chord sequence was found. Try a cleaner recording or manual edits."\n',
    '        )\n',
    '    elif mean_confidence < 0.42:\n',
    '        warnings.append("Overall chord confidence is low; verify the timeline by ear.")\n',
    '    if mean_tonality < 0.11:\n',
    '        warnings.append(\n',
    '            "The recording is harmonically dense or noisy, which weakens chord estimates."\n',
    '        )\n',
    '    if abs(tuning_cents) >= 25:\n',
    '        warnings.append(\n',
    '            f"The recording is about {abs(tuning_cents):.0f} cents {\'sharp\' if tuning_cents > 0 else \'flat\'} of A=440."\n',
    '        )\n',
    '    if drone_root is not None:\n',
    '        warnings.append(\n',
    '            f"A sustained {pitch_name(drone_root, key_prefers_flats(dominant_key))} drone was detected and partly removed before chord scoring."\n',
    '        )\n',
    '    if len(key_regions) > 1:\n',
    '        warnings.append(\n',
    '            "Multiple tonal regions were detected; use the local-key labels rather than assuming one key for the whole song."\n',
    '        )\n',
    '    if ratio is not None and ratio < 0.70:\n',
    '        warnings.append(\n',
    '            f"Only about {ratio:.0%} of chord duration fits the dominant {dominant_key} region; the song may be modal, modulating, or use borrowed harmony."\n',
    '        )\n',
    '    if meter_confidence < 0.28 and meter_override is None:\n',
    '        warnings.append(\n',
    '            "The bar-line estimate is uncertain. Set beats per bar manually if the chart groups beats incorrectly."\n',
    '        )\n',
    '    return AnalyzerOutput(\n',
    '        duration=duration,\n',
    '        tempo_bpm=tempo,\n',
    '        tempo_confidence=tempo_confidence,\n',
    '        meter=meter,\n',
    '        meter_confidence=meter_confidence,\n',
    '        key=dominant_key,\n',
    '        key_confidence=key_confidence,\n',
    '        tuning_cents=tuning_cents,\n',
    '        segments=segments,\n',
    '        beats=beats,\n',
    '        key_regions=key_regions,\n',
    '        patterns=patterns,\n',
    '        drone=(\n',
    '            pitch_name(drone_root, key_prefers_flats(dominant_key))\n',
    '            if drone_root is not None\n',
    '            else None\n',
    '        ),\n',
    '        drone_confidence=drone_confidence,\n',
    '        warnings=warnings,\n',
    '        used_beat_tracking=used_beats,\n',
    '    )\n',
], append=True)

put('src/sgchords/audio.py', [
    'from __future__ import annotations\n',
    '\n',
    'import json\n',
    'import os\n',
    'import re\n',
    'import shutil\n',
    'import subprocess\n',
    'from dataclasses import dataclass\n',
    'from pathlib import Path\n',
    'from typing import Any\n',
    'from urllib.parse import urlparse\n',
    '\n',
    'YOUTUBE_HOSTS = {\n',
    '    "youtube.com",\n',
    '    "www.youtube.com",\n',
    '    "m.youtube.com",\n',
    '    "music.youtube.com",\n',
    '    "youtu.be",\n',
    '    "www.youtube-nocookie.com",\n',
    '}\n',
    '\n',
    '\n',
    'class InputError(ValueError):\n',
    '    pass\n',
    '\n',
    '\n',
    'class DependencyError(RuntimeError):\n',
    '    pass\n',
    '\n',
    '\n',
    '@dataclass(slots=True)\n',
    'class PreparedAudio:\n',
    '    path: Path\n',
    '    title: str\n',
    '    source: str\n',
    '    duration: float\n',
    '\n',
    '\n',
    'def is_youtube_url(value: str) -> bool:\n',
    '    try:\n',
    '        parsed = urlparse(value.strip())\n',
    '    except ValueError:\n',
    '        return False\n',
    '    return parsed.scheme in {"http", "https"} and (parsed.hostname or "").lower() in YOUTUBE_HOSTS\n',
    '\n',
    '\n',
    'def require_binary(name: str) -> str:\n',
    '    path = shutil.which(name)\n',
    '    if path is None:\n',
    '        raise DependencyError(\n',
    '            f"{name} is required. Install FFmpeg and put ffmpeg and ffprobe on PATH."\n',
    '        )\n',
    '    return path\n',
    '\n',
    '\n',
    'def probe_duration(path: str | Path) -> float:\n',
    '    command = [\n',
    '        require_binary("ffprobe"),\n',
    '        "-v",\n',
    '        "error",\n',
    '        "-show_entries",\n',
    '        "format=duration",\n',
    '        "-of",\n',
    '        "json",\n',
    '        str(path),\n',
    '    ]\n',
    '    process = subprocess.run(command, capture_output=True, text=True, check=False, timeout=30)\n',
    '    if process.returncode != 0:\n',
    '        raise InputError(process.stderr.strip() or "ffprobe could not read this file")\n',
    '    try:\n',
    '        duration = float(json.loads(process.stdout)["format"]["duration"])\n',
    '    except (KeyError, TypeError, ValueError, json.JSONDecodeError) as exc:\n',
    '        raise InputError("Could not determine media duration.") from exc\n',
    '    if duration <= 0:\n',
    '        raise InputError("The media file has no readable audio duration.")\n',
    '    return duration\n',
    '\n',
    '\n',
    'def normalize_audio(source: str | Path, destination: str | Path) -> Path:\n',
    '    destination = Path(destination)\n',
    '    destination.parent.mkdir(parents=True, exist_ok=True)\n',
    '    command = [\n',
    '        require_binary("ffmpeg"),\n',
    '        "-hide_banner",\n',
    '        "-loglevel",\n',
    '        "error",\n',
    '        "-y",\n',
    '        "-i",\n',
    '        str(source),\n',
    '        "-map",\n',
    '        "0:a:0",\n',
    '        "-vn",\n',
    '        "-ac",\n',
    '        "1",\n',
    '        "-ar",\n',
    '        "22050",\n',
    '        "-c:a",\n',
    '        "pcm_s16le",\n',
    '        str(destination),\n',
    '    ]\n',
    '    process = subprocess.run(command, capture_output=True, text=True, check=False, timeout=240)\n',
    '    if process.returncode != 0 or not destination.exists():\n',
    '        details = process.stderr.strip().splitlines()\n',
    '        raise InputError(details[-1] if details else "FFmpeg could not decode the audio.")\n',
    '    return destination\n',
    '\n',
    '\n',
    'def _safe_title(value: str) -> str:\n',
    '    return re.sub(r"[\\x00-\\x1f]+", " ", value).strip()[:160] or "Untitled song"\n',
    '\n',
    '\n',
    'def prepare_local_audio(\n',
    '    source: str | Path,\n',
    '    workdir: str | Path,\n',
    '    *,\n',
    '    max_duration_seconds: int = 1200,\n',
    '    max_file_bytes: int = 600 * 1024 * 1024,\n',
    ') -> PreparedAudio:\n',
    '    source_path = Path(source)\n',
    '    if not source_path.is_file():\n',
    '        raise InputError("Choose an existing audio or video file.")\n',
    '    if source_path.stat().st_size > max_file_bytes:\n',
    '        raise InputError("The uploaded file is too large (limit: 600 MB).")\n',
    '    duration = probe_duration(source_path)\n',
    '    if duration > max_duration_seconds:\n',
    '        raise InputError(\n',
    '            f"This file is {duration / 60:.1f} minutes; the limit is {max_duration_seconds / 60:.0f} minutes."\n',
    '        )\n',
    '    destination = Path(workdir) / "source.wav"\n',
    '    normalize_audio(source_path, destination)\n',
    '    return PreparedAudio(destination, _safe_title(source_path.stem), str(source_path), duration)\n',
    '\n',
    '\n',
    'def _downloaded_path(info: dict[str, Any], ydl: Any, workdir: Path) -> Path:\n',
    '    for item in info.get("requested_downloads") or []:\n',
    '        if item.get("filepath") and Path(item["filepath"]).is_file():\n',
    '            return Path(item["filepath"])\n',
    '    prepared = Path(ydl.prepare_filename(info))\n',
    '    if prepared.is_file():\n',
    '        return prepared\n',
    '    candidates = [path for path in workdir.glob("download.*") if path.is_file()]\n',
    '    if not candidates:\n',
    '        raise InputError("YouTube audio was downloaded but the output file was not found.")\n',
    '    return max(candidates, key=lambda path: path.stat().st_mtime)\n',
    '\n',
    '\n',
    'def prepare_youtube_audio(\n',
    '    url: str, workdir: str | Path, *, max_duration_seconds: int = 1200\n',
    ') -> PreparedAudio:\n',
    '    if not is_youtube_url(url):\n',
    '        raise InputError("Enter a full youtube.com or youtu.be URL.")\n',
    '    try:\n',
    '        import yt_dlp\n',
    '    except ImportError as exc:\n',
    '        raise DependencyError("yt-dlp is not installed. Run `uv sync --locked`.") from exc\n',
    '    workdir = Path(workdir)\n',
    '    workdir.mkdir(parents=True, exist_ok=True)\n',
    '\n',
    '    def reject(info: dict[str, Any], *, incomplete: bool) -> str | None:\n',
    '        del incomplete\n',
    '        if info.get("is_live"):\n',
    '            return "Live streams are not supported."\n',
    '        if info.get("duration") and float(info["duration"]) > max_duration_seconds:\n',
    '            return f"Video exceeds the {max_duration_seconds / 60:.0f}-minute limit."\n',
    '        return None\n',
    '\n',
    '    options: dict[str, Any] = {\n',
    '        "format": "bestaudio/best",\n',
    '        "outtmpl": str(workdir / "download.%(ext)s"),\n',
    '        "noplaylist": True,\n',
    '        "quiet": True,\n',
    '        "no_warnings": True,\n',
    '        "socket_timeout": 30,\n',
    '        "retries": 3,\n',
    '        "fragment_retries": 3,\n',
    '        "extractor_retries": 2,\n',
    '        "match_filter": reject,\n',
    '        "restrictfilenames": True,\n',
    '    }\n',
    '    cookie_file = os.getenv("SGCHORDS_COOKIES_FILE")\n',
    '    if cookie_file:\n',
    '        cookie_path = Path(cookie_file).expanduser()\n',
    '        if not cookie_path.is_file():\n',
    '            raise DependencyError("SGCHORDS_COOKIES_FILE is not readable.")\n',
    '        options["cookiefile"] = str(cookie_path)\n',
    '    try:\n',
    '        with yt_dlp.YoutubeDL(options) as ydl:\n',
    '            raw = ydl.extract_info(url.strip(), download=True)\n',
    '            if not raw or raw.get("_type") == "playlist":\n',
    '                raise InputError("Provide one video, not a playlist.")\n',
    '            info = ydl.sanitize_info(raw)\n',
    '            downloaded = _downloaded_path(info, ydl, workdir)\n',
    '    except yt_dlp.utils.DownloadError as exc:\n',
    '        message = str(exc).replace("ERROR:", "").strip()\n',
    '        raise InputError(\n',
    '            f"YouTube download failed: {message}. Update the lockfile or use a local file; some videos require cookies."\n',
    '        ) from exc\n',
    '    duration = float(info.get("duration") or probe_duration(downloaded))\n',
    '    if duration > max_duration_seconds:\n',
    '        raise InputError(f"Video exceeds the {max_duration_seconds / 60:.0f}-minute limit.")\n',
    '    destination = workdir / "source.wav"\n',
    '    normalize_audio(downloaded, destination)\n',
    '    return PreparedAudio(\n',
    '        destination, _safe_title(str(info.get("title") or "YouTube song")), url.strip(), duration\n',
    '    )\n',
], append=False)

put('src/sgchords/chords.py', [
    'from __future__ import annotations\n',
    '\n',
    'import html\n',
    'import re\n',
    'from collections.abc import Iterable, Sequence\n',
    'from dataclasses import dataclass\n',
    'from functools import lru_cache\n',
    '\n',
    'import numpy as np\n',
    '\n',
    'from .models import ChordSegment\n',
    '\n',
    'SHARP_NAMES = ("C", "C#", "D", "D#", "E", "F", "F#", "G", "G#", "A", "A#", "B")\n',
    'FLAT_NAMES = ("C", "Db", "D", "Eb", "E", "F", "Gb", "G", "Ab", "A", "Bb", "B")\n',
    'PITCH_CLASS = {\n',
    '    "C": 0,\n',
    '    "B#": 0,\n',
    '    "C#": 1,\n',
    '    "Db": 1,\n',
    '    "D": 2,\n',
    '    "D#": 3,\n',
    '    "Eb": 3,\n',
    '    "E": 4,\n',
    '    "Fb": 4,\n',
    '    "E#": 5,\n',
    '    "F": 5,\n',
    '    "F#": 6,\n',
    '    "Gb": 6,\n',
    '    "G": 7,\n',
    '    "G#": 8,\n',
    '    "Ab": 8,\n',
    '    "A": 9,\n',
    '    "A#": 10,\n',
    '    "Bb": 10,\n',
    '    "B": 11,\n',
    '    "Cb": 11,\n',
    '}\n',
    '\n',
    'MODE_INTERVALS: dict[str, tuple[int, ...]] = {\n',
], append=False)
