from __future__ import annotations

from pathlib import Path


def put(path: str, lines: list[str], *, append: bool = False) -> None:
    target = Path(path)
    target.parent.mkdir(parents=True, exist_ok=True)
    mode = "a" if append else "w"
    with target.open(mode, encoding="utf-8", newline="") as handle:
        handle.writelines(lines)


put('src/sgchords/chords.py', [
    '        # Avoid labeling ordinary major/minor material modal unless the characteristic pitch is present.\n',
], append=True)

put('src/sgchords/chords.py', [
    '        if candidate.mode in {"dorian", "mixolydian", "phrygian"}:\n',
    '            characteristic = {"dorian": 9, "mixolydian": 10, "phrygian": 1}[candidate.mode]\n',
    '            mass = np.maximum(values, 0) / (float(np.sum(np.maximum(values, 0))) + 1e-12)\n',
    '            score += 0.08 * float(mass[(candidate.root + characteristic) % 12]) - 0.018\n',
    '        scores.append(score)\n',
    '    return candidates, np.asarray(scores)\n',
    '\n',
    '\n',
    'def estimate_key(global_chroma: np.ndarray) -> tuple[str, float, int, str]:\n',
    '    candidates, scores = tonality_scores(global_chroma)\n',
    '    if not np.any(scores):\n',
    '        return "Unknown", 0.0, 0, "major"\n',
    '    order = np.argsort(scores)[::-1]\n',
    '    best = candidates[int(order[0])]\n',
    '    margin = float(scores[order[0]] - scores[order[1]]) if len(order) > 1 else 0.0\n',
    '    return best.label, float(np.clip(margin / 0.20, 0.0, 1.0)), best.root, best.mode\n',
    '\n',
    '\n',
    'def _triad_quality(intervals: tuple[int, int, int]) -> str:\n',
    '    shape = ((intervals[1] - intervals[0]) % 12, (intervals[2] - intervals[0]) % 12)\n',
    '    if shape == (4, 7):\n',
    '        return "maj"\n',
    '    if shape == (3, 7):\n',
    '        return "min"\n',
    '    if shape == (3, 6):\n',
    '        return "dim"\n',
    '    return "other"\n',
    '\n',
    '\n',
    '@lru_cache(maxsize=8)\n',
    'def mode_diatonic_triads(mode: str) -> tuple[tuple[int, str], ...]:\n',
    '    scale = MODE_INTERVALS.get(mode, MODE_INTERVALS["major"])\n',
    '    result: list[tuple[int, str]] = []\n',
    '    for degree in range(7):\n',
    '        notes = tuple(\n',
    '            scale[index % 7] + (12 if index >= 7 else 0)\n',
    '            for index in (degree, degree + 2, degree + 4)\n',
    '        )\n',
    '        root = notes[0] % 12\n',
    '        normalized = (0, (notes[1] - notes[0]) % 12, (notes[2] - notes[0]) % 12)\n',
    '        result.append((root, _triad_quality(normalized)))\n',
    '    return tuple(result)\n',
    '\n',
    '\n',
    'def is_diatonic(spec: ChordSpec, key_root: int, key_mode: str) -> bool:\n',
    '    relative = (spec.root - key_root) % 12\n',
    '    triad = dict(mode_diatonic_triads(key_mode)).get(relative)\n',
    '    if triad is None:\n',
    '        return False\n',
    '    if spec.quality == triad:\n',
    '        return True\n',
    '    if spec.quality == "7" and relative == 7:\n',
    '        return True\n',
    '    if spec.quality == "min7" and triad == "min":\n',
    '        return True\n',
    '    if spec.quality == "maj7" and triad == "maj":\n',
    '        return True\n',
    '    return spec.quality in {"sus2", "sus4", "power"}\n',
    '\n',
    '\n',
    'def _degree_and_accidental(pitch: int, key_root: int, mode: str) -> tuple[int, str]:\n',
    '    scale = MODE_INTERVALS.get(mode, MODE_INTERVALS["major"])\n',
    '    relative = (pitch - key_root) % 12\n',
    '    if relative in scale:\n',
    '        return scale.index(relative) + 1, ""\n',
    '    distances: list[tuple[int, int, str]] = []\n',
    '    for index, note in enumerate(scale):\n',
    '        if (note - 1) % 12 == relative:\n',
    '            distances.append((0, index + 1, "♭"))\n',
    '        if (note + 1) % 12 == relative:\n',
    '            distances.append((0, index + 1, "♯"))\n',
    '    if distances:\n',
    '        _distance, degree, accidental = distances[0]\n',
    '        return degree, accidental\n',
    '    nearest = min(\n',
    '        range(7),\n',
    '        key=lambda index: min((relative - scale[index]) % 12, (scale[index] - relative) % 12),\n',
    '    )\n',
    '    return nearest + 1, ""\n',
    '\n',
    '\n',
    'def roman_numeral(chord: str, key: str) -> str:\n',
    '    parsed = parse_chord(chord)\n',
    '    parsed_key = parse_key(key)\n',
    '    if parsed is None or parsed_key is None:\n',
    '        return chord\n',
    '    degree, accidental = _degree_and_accidental(parsed.root, *parsed_key)\n',
    '    symbol = ("I", "II", "III", "IV", "V", "VI", "VII")[degree - 1]\n',
    '    quality = _suffix_quality(parsed.suffix)\n',
    '    if quality in {"min", "min7", "min6"}:\n',
    '        symbol = symbol.lower()\n',
    '    elif quality == "dim":\n',
    '        symbol = symbol.lower() + "°"\n',
    '    elif quality == "aug":\n',
    '        symbol += "+"\n',
    '    if quality in {"7", "maj7", "min7"}:\n',
    '        symbol += "7"\n',
    '    result = accidental + symbol\n',
    '    if parsed.bass is not None:\n',
    '        bass_degree, bass_accidental = _degree_and_accidental(parsed.bass, *parsed_key)\n',
    '        result += f"/{bass_accidental}{(\'I\', \'II\', \'III\', \'IV\', \'V\', \'VI\', \'VII\')[bass_degree - 1]}"\n',
    '    return result\n',
    '\n',
    '\n',
    'def nashville_number(chord: str, key: str) -> str:\n',
    '    parsed = parse_chord(chord)\n',
    '    parsed_key = parse_key(key)\n',
    '    if parsed is None or parsed_key is None:\n',
    '        return chord\n',
    '    degree, accidental = _degree_and_accidental(parsed.root, *parsed_key)\n',
    '    accidental = accidental.replace("♭", "b").replace("♯", "#")\n',
    '    quality = _suffix_quality(parsed.suffix)\n',
    '    suffix = {\n',
    '        "min": "m",\n',
    '        "min7": "m7",\n',
    '        "min6": "m6",\n',
    '        "dim": "dim",\n',
    '        "aug": "+",\n',
    '        "7": "7",\n',
    '        "maj7": "maj7",\n',
    '        "sus2": "sus2",\n',
    '        "sus4": "sus4",\n',
    '    }.get(quality, "")\n',
    '    result = f"{accidental}{degree}{suffix}"\n',
    '    if parsed.bass is not None:\n',
    '        bass_degree, bass_accidental = _degree_and_accidental(parsed.bass, *parsed_key)\n',
    '        bass_accidental = bass_accidental.replace("♭", "b").replace("♯", "#")\n',
    '        result += f"/{bass_accidental}{bass_degree}"\n',
    '    return result\n',
    '\n',
    '\n',
    'def format_chord_notation(chord: str, key: str, notation: str) -> str:\n',
    '    return (\n',
    '        roman_numeral(chord, key)\n',
    '        if notation == "roman"\n',
    '        else nashville_number(chord, key)\n',
    '        if notation == "nashville"\n',
    '        else chord\n',
    '    )\n',
    '\n',
    '\n',
    'def shape_lookup(chord: str, instrument: str) -> tuple[str, str] | None:\n',
    '    shapes = GUITAR_SHAPES if instrument.lower() == "guitar" else UKULELE_SHAPES\n',
    '    parsed = parse_chord(chord)\n',
    '    if parsed is None:\n',
    '        return None\n',
    '    candidates = [\n',
    '        chord.split("/")[0],\n',
    '        f"{pitch_name(parsed.root, True)}{parsed.suffix}",\n',
    '        f"{pitch_name(parsed.root, False)}{parsed.suffix}",\n',
    '    ]\n',
    '    # Fall back to the triad when a detailed voicing is absent.\n',
    '    simplified = simplify_chord(chord)\n',
    '    candidates.extend(\n',
    '        [simplified, transpose_chord(simplified, 0, True), transpose_chord(simplified, 0, False)]\n',
    '    )\n',
    '    for candidate in dict.fromkeys(candidates):\n',
    '        if candidate in shapes:\n',
    '            return candidate, shapes[candidate]\n',
    '    return None\n',
    '\n',
    '\n',
    'def render_chord_shapes(chords: Iterable[str], instrument: str) -> str:\n',
    '    unique = list(dict.fromkeys(chord for chord in chords if chord != "N"))\n',
    '    tuning = "E A D G B E (low to high)" if instrument == "guitar" else "G C E A"\n',
    '    lines = [f"{instrument.title()} tuning: {tuning}", ""]\n',
    '    for chord in unique:\n',
    '        shape = shape_lookup(chord, instrument)\n',
    '        lines.append(f"{chord}: {shape[1] if shape else \'no built-in voicing\'}")\n',
    '    return "\\n".join(lines) if unique else "No playable chord shapes were detected."\n',
    '\n',
    '\n',
    'def _shape_svg(label: str, frets: str, instrument: str) -> str:\n',
    '    strings = 6 if instrument == "guitar" else 4\n',
    '    values = list(frets)\n',
    '    if len(values) != strings:\n',
    '        return ""\n',
    '    numeric = [int(value) for value in values if value.isdigit() and int(value) > 0]\n',
    '    base_fret = max(1, min(numeric) if numeric and max(numeric) > 4 else 1)\n',
    '    width, height = 118, 150\n',
    '    left, top, grid_w, grid_h = 20, 32, 78, 92\n',
    '    string_gap = grid_w / (strings - 1)\n',
    '    fret_gap = grid_h / 5\n',
    '    parts = [\n',
    '        f\'<div class="sg-diagram-card"><svg viewBox="0 0 {width} {height}" role="img" aria-label="{html.escape(label)} chord diagram">\',\n',
    '        f\'<text class="sg-diagram-title" x="59" y="17" text-anchor="middle">{html.escape(label)}</text>\',\n',
    '    ]\n',
    '    for string in range(strings):\n',
    '        x = left + string * string_gap\n',
    '        parts.append(f\'<line x1="{x:.1f}" y1="{top}" x2="{x:.1f}" y2="{top + grid_h}"/>\')\n',
    '    for fret in range(6):\n',
    '        y = top + fret * fret_gap\n',
    '        stroke = 3 if fret == 0 and base_fret == 1 else 1\n',
    '        parts.append(\n',
    '            f\'<line x1="{left}" y1="{y:.1f}" x2="{left + grid_w}" y2="{y:.1f}" stroke-width="{stroke}"/>\'\n',
    '        )\n',
    '    if base_fret > 1:\n',
    '        parts.append(\n',
    '            f\'<text class="sg-fret-label" x="4" y="{top + fret_gap:.1f}">{base_fret}fr</text>\'\n',
    '        )\n',
    '    for string, value in enumerate(values):\n',
    '        x = left + string * string_gap\n',
    '        if value.lower() == "x":\n',
    '            parts.append(\n',
    '                f\'<text class="sg-marker" x="{x:.1f}" y="27" text-anchor="middle">×</text>\'\n',
    '            )\n',
    '        elif value == "0":\n',
    '            parts.append(f\'<circle class="sg-open" cx="{x:.1f}" cy="24" r="4"/>\')\n',
    '        elif value.isdigit():\n',
    '            displayed = int(value) - base_fret + 1\n',
    '            if 1 <= displayed <= 5:\n',
    '                y = top + (displayed - 0.5) * fret_gap\n',
    '                parts.append(f\'<circle class="sg-finger" cx="{x:.1f}" cy="{y:.1f}" r="5"/>\')\n',
    '    parts.append("</svg></div>")\n',
    '    return "".join(parts)\n',
    '\n',
    '\n',
    'def render_chord_diagrams_html(chords: Iterable[str], instrument: str) -> str:\n',
    '    unique = list(dict.fromkeys(chord for chord in chords if chord != "N"))\n',
    '    diagrams: list[str] = []\n',
    '    missing: list[str] = []\n',
    '    for chord in unique:\n',
    '        shape = shape_lookup(chord, instrument)\n',
    '        if shape is None:\n',
    '            missing.append(chord)\n',
    '        else:\n',
    '            diagrams.append(_shape_svg(chord, shape[1], instrument))\n',
    '    if missing:\n',
    '        diagrams.append(\n',
    '            f\'<div class="sg-missing-shapes">No built-in diagram: {html.escape(", ".join(missing))}</div>\'\n',
    '        )\n',
    '    return (\n',
    '        \'<div class="sg-diagram-grid">\' + "".join(diagrams) + "</div>"\n',
    '        if diagrams\n',
    '        else "<p>No chord diagrams.</p>"\n',
    '    )\n',
    '\n',
    '\n',
    'def suggest_capo(\n',
    '    segments: Sequence[ChordSegment], instrument: str = "guitar", max_capo: int = 7\n',
    ') -> tuple[int, list[str], float]:\n',
    '    weighted = [\n',
    '        (simplify_chord(segment.chord), max(segment.duration, 0.1))\n',
    '        for segment in segments\n',
    '        if segment.chord != "N"\n',
    '    ]\n',
    '    if not weighted:\n',
    '        return 0, [], 0.0\n',
    '    total = sum(duration for _chord, duration in weighted)\n',
    '    easy = GUITAR_EASY if instrument == "guitar" else UKULELE_EASY\n',
    '    best: tuple[float, int, list[str]] | None = None\n',
    '    for capo in range(max_capo + 1):\n',
    '        shapes: list[str] = []\n',
    '        cost = 0.0\n',
    '        for sounding, duration in weighted:\n',
    '            played = transpose_chord(sounding, -capo, prefer_flats=True)\n',
    '            lookup = shape_lookup(played, instrument)\n',
    '            canonical = lookup[0] if lookup else played\n',
    '            shapes.append(canonical)\n',
    '            cost += (0.10 if canonical in easy else 0.60 if lookup else 1.35) * duration\n',
    '        cost += capo * total * 0.028\n',
    '        candidate = (cost, capo, list(dict.fromkeys(shapes)))\n',
    '        if best is None or candidate[0] < best[0]:\n',
    '            best = candidate\n',
    '    assert best is not None\n',
    '    return best[1], best[2], float(np.clip(1.0 - best[0] / (1.35 * total), 0.0, 1.0))\n',
], append=True)

put('src/sgchords/cli.py', [
    'from __future__ import annotations\n',
    '\n',
    'import argparse\n',
    'import shutil\n',
    'import sys\n',
    'from pathlib import Path\n',
    '\n',
    'from .audio import is_youtube_url\n',
    'from .chords import suggest_capo\n',
    'from .exports import render_bar_chart, render_summary, write_exports\n',
    'from .service import analyze_request\n',
    '\n',
    '\n',
    'def build_parser() -> argparse.ArgumentParser:\n',
    '    parser = argparse.ArgumentParser(\n',
    '        prog="sgchords",\n',
    '        description="Estimate synchronized chords from a YouTube URL or local media file.",\n',
    '    )\n',
    '    parser.add_argument("source", help="YouTube URL or local audio/video path")\n',
    '    parser.add_argument(\n',
    '        "-o",\n',
    '        "--output-dir",\n',
    '        type=Path,\n',
    '        default=Path("sgchords-output"),\n',
    '        help="Export directory",\n',
    '    )\n',
    '    parser.add_argument(\n',
    '        "--detail", choices=("simple", "standard", "detailed"), default="standard"\n',
    '    )\n',
    '    parser.add_argument("--smoothing", type=float, default=0.68)\n',
    '    parser.add_argument(\n',
    '        "--meter",\n',
    '        choices=("auto", "3", "4", "6"),\n',
    '        default="auto",\n',
    '        help="Auto-detect or force beats per bar",\n',
    '    )\n',
    '    parser.add_argument(\n',
    '        "--transpose", type=int, default=0, choices=range(-11, 12), metavar="[-11..11]"\n',
    '    )\n',
    '    parser.add_argument("--capo", type=int, default=0, choices=range(0, 8))\n',
    '    parser.add_argument(\n',
    '        "--notation", choices=("standard", "roman", "nashville"), default="standard"\n',
    '    )\n',
    '    parser.add_argument(\n',
    '        "--instrument", choices=("guitar", "ukulele"), default="guitar"\n',
    '    )\n',
    '    return parser\n',
    '\n',
    '\n',
    'def main(argv: list[str] | None = None) -> int:\n',
    '    parser = build_parser()\n',
    '    args = parser.parse_args(argv)\n',
    '    if not 0 <= args.smoothing <= 1:\n',
    '        parser.error("--smoothing must be between 0 and 1")\n',
    '    args.output_dir.mkdir(parents=True, exist_ok=True)\n',
    '    workspace = args.output_dir / ".work"\n',
    '    try:\n',
    '        result, job_dir = analyze_request(\n',
    '            youtube_url=args.source if is_youtube_url(args.source) else None,\n',
    '            upload_path=None if is_youtube_url(args.source) else args.source,\n',
    '            detail=args.detail,\n',
    '            smoothing=args.smoothing,\n',
    '            meter_override=None if args.meter == "auto" else int(args.meter),\n',
    '            workspace_root=workspace,\n',
    '        )\n',
    '        files = write_exports(\n',
    '            result,\n',
    '            args.output_dir,\n',
    '            transpose=args.transpose,\n',
    '            capo=args.capo,\n',
    '            notation=args.notation,\n',
    '            instrument=args.instrument,\n',
    '        )\n',
    '        auto_capo, shapes, ease = suggest_capo(result.segments, args.instrument)\n',
    '        print(\n',
    '            render_summary(\n',
    '                result,\n',
    '                result.segments,\n',
    '                instrument=args.instrument,\n',
    '                transpose=args.transpose,\n',
    '                capo=args.capo,\n',
    '                notation=args.notation,\n',
    '            )\n',
    '        )\n',
    '        print("\\n" + render_bar_chart(\n',
    '            result,\n',
    '            result.segments,\n',
    '            transpose=args.transpose,\n',
    '            capo=args.capo,\n',
    '            notation=args.notation,\n',
    '        ))\n',
    '        print(\n',
    '            f"\\nAutomatic {args.instrument} capo suggestion: {auto_capo}; "\n',
    '            f"shapes {\', \'.join(shapes) or \'none\'}; ease {ease:.0%}."\n',
    '        )\n',
    '        print("\\nCreated:")\n',
    '        for file in files:\n',
    '            print(f"  {file}")\n',
    '        shutil.rmtree(job_dir, ignore_errors=True)\n',
    '        return 0\n',
    '    except Exception as exc:\n',
    '        print(f"sgchords: {exc}", file=sys.stderr)\n',
    '        return 1\n',
    '\n',
    '\n',
    'if __name__ == "__main__":\n',
    '    raise SystemExit(main())\n',
], append=False)
