from __future__ import annotations

from pathlib import Path


def put(path: str, lines: list[str], *, append: bool = False) -> None:
    target = Path(path)
    target.parent.mkdir(parents=True, exist_ok=True)
    mode = "a" if append else "w"
    with target.open(mode, encoding="utf-8", newline="") as handle:
        handle.writelines(lines)


put('src/sgchords/ui.py', [
    '        summary, player, chart, diagrams = _views(\n',
], append=True)

put('src/sgchords/ui.py', [
    '            result,\n',
    '            rows_to_segments(timeline),\n',
    '            transpose=int(transpose),\n',
    '            capo=int(capo),\n',
    '            notation=notation,\n',
    '            instrument=instrument,\n',
    '            meter_override=_meter(meter_override),\n',
    '        )\n',
    '        return (\n',
    '            "Views and downloads regenerated from the edited timeline.",\n',
    '            summary,\n',
    '            player,\n',
    '            chart,\n',
    '            diagrams,\n',
    '            files,\n',
    '        )\n',
    '    except Exception as exc:\n',
    '        raise gr.Error(str(exc)) from exc\n',
    '\n',
    '\n',
    'def _quantize_ui(timeline: Any, state: dict[str, Any]) -> pd.DataFrame:\n',
    '    if not state:\n',
    '        raise gr.Error("Analyze a song first.")\n',
    '    result = AnalysisResult.from_state(state)\n',
    '    return _timeline_frame(\n',
    '        quantize_segments(rows_to_segments(timeline), result.beats, duration=result.duration)\n',
    '    )\n',
    '\n',
    '\n',
    'def _merge_ui(timeline: Any) -> pd.DataFrame:\n',
    '    return _timeline_frame(merge_adjacent_segments(rows_to_segments(timeline)))\n',
    '\n',
    '\n',
    'def build_demo() -> gr.Blocks:\n',
    '    with gr.Blocks(\n',
    '        title="SgChords", delete_cache=(86_400, 86_400), analytics_enabled=False\n',
    '    ) as demo:\n',
    '        gr.HTML(\n',
    '            "<section class=\'sg-hero\'><h1>SgChords</h1><p>Turn a YouTube link or recording into a synchronized, editable guitar or ukulele play-along chart. Chords, local tonal regions, bars, confidence, capo shapes and transposition stay visible.</p></section>"\n',
    '        )\n',
    '        with gr.Row():\n',
    '            with gr.Column(scale=3, elem_classes="sg-card"):\n',
    '                youtube_url = gr.Textbox(\n',
    '                    label="YouTube URL",\n',
    '                    placeholder="https://www.youtube.com/watch?v=...",\n',
    '                    info="Leave blank when uploading a file.",\n',
    '                )\n',
    '                upload = gr.File(\n',
    '                    label="Or upload audio/video",\n',
    '                    file_types=["audio", "video", ".m4a", ".webm", ".mp4"],\n',
    '                    type="filepath",\n',
    '                )\n',
    '            with gr.Column(scale=2, elem_classes="sg-card"):\n',
    '                detail = gr.Radio(\n',
    '                    choices=[\n',
    '                        ("Simple — major/minor", "simple"),\n',
    '                        ("Standard — 7, maj7, m7, sus, dim", "standard"),\n',
    '                        ("Detailed — adds 6, add9, aug and power", "detailed"),\n',
    '                    ],\n',
    '                    value="standard",\n',
    '                    label="Chord vocabulary",\n',
    '                )\n',
    '                smoothing = gr.Slider(\n',
    '                    0,\n',
    '                    1,\n',
    '                    value=0.68,\n',
    '                    step=0.05,\n',
    '                    label="Sequence smoothing",\n',
    '                    info="Higher removes flicker; lower preserves fast changes.",\n',
    '                )\n',
    '                with gr.Row():\n',
    '                    meter_override = gr.Dropdown(\n',
    '                        ["Auto", "3", "4", "6"], value="Auto", label="Beats per bar"\n',
    '                    )\n',
    '                    instrument = gr.Radio(\n',
    '                        [("Guitar", "guitar"), ("Ukulele", "ukulele")],\n',
    '                        value="guitar",\n',
    '                        label="Instrument",\n',
    '                    )\n',
    '        with gr.Row():\n',
    '            analyze_button = gr.Button("Analyze song", variant="primary", size="lg")\n',
    '            clear_button = gr.ClearButton(value="Clear", size="lg")\n',
    '        gr.Markdown(\n',
    '            "Automatic transcription is a draft. Local-key and drone tracking reduce common folk-music errors, but modal tunes and noisy field recordings still need your ear.",\n',
    '            elem_classes="sg-note",\n',
    '        )\n',
    '        status = gr.Markdown()\n',
    '        state = gr.State({})\n',
    '        with gr.Tab("Play along"):\n',
    '            with gr.Row():\n',
    '                with gr.Column(scale=2):\n',
    '                    audio_preview = gr.Audio(\n',
    '                        label="Normalized source",\n',
    '                        type="filepath",\n',
    '                        interactive=False,\n',
    '                        editable=False,\n',
    '                        elem_id="sg-audio-player",\n',
    '                    )\n',
    '                with gr.Column(scale=3):\n',
    '                    summary = gr.Markdown()\n',
    '            player = SyncedChordViewer()\n',
    '            with gr.Row():\n',
    '                transpose = gr.Slider(\n',
    '                    -11,\n',
    '                    11,\n',
    '                    value=0,\n',
    '                    step=1,\n',
    '                    label="Concert transpose",\n',
    '                    info="Keep 0 to play with the original audio.",\n',
    '                )\n',
    '                capo = gr.Slider(\n',
    '                    0,\n',
    '                    7,\n',
    '                    value=0,\n',
    '                    step=1,\n',
    '                    label="Capo fret",\n',
    '                    info="Changes shapes, not sounding pitch.",\n',
    '                )\n',
    '                notation = gr.Radio(\n',
    '                    [\n',
    '                        ("Chord names", "standard"),\n',
    '                        ("Roman numerals", "roman"),\n',
    '                        ("Nashville numbers", "nashville"),\n',
    '                    ],\n',
    '                    value="standard",\n',
    '                    label="Display notation",\n',
    '                )\n',
    '        with gr.Tab("Chord chart"):\n',
    '            chart = gr.Code(\n',
    '                label="Beat-aligned chart",\n',
    '                language=None,\n',
    '                lines=20,\n',
    '                interactive=False,\n',
    '                elem_classes="sg-output",\n',
    '            )\n',
    '            diagrams = gr.HTML(label="Chord diagrams")\n',
    '        with gr.Tab("Edit timeline"):\n',
    '            gr.Markdown(\n',
    '                "Edit concert chord names. Quantize snaps boundaries to detected beats; merge joins adjacent repeats."\n',
    '            )\n',
    '            timeline = gr.Dataframe(\n',
    '                headers=HEADERS,\n',
    '                datatype=["number", "number", "str", "number", "str", "number", "number"],\n',
    '                type="pandas",\n',
    '                interactive=True,\n',
    '                wrap=True,\n',
    '                label="Editable timeline",\n',
    '                show_row_numbers=True,\n',
    '            )\n',
    '            with gr.Row():\n',
    '                quantize_button = gr.Button("Quantize to beats")\n',
    '                merge_button = gr.Button("Merge repeats")\n',
    '                apply_button = gr.Button("Apply edits to player", variant="secondary")\n',
    '        with gr.Tab("Downloads"):\n',
    '            export_button = gr.Button("Regenerate all downloads", variant="primary")\n',
    '            downloads = gr.File(\n',
    '                label="Text, CSV, JSON, ChordPro, shapes, SRT and LAB",\n',
    '                file_count="multiple",\n',
    '                interactive=False,\n',
    '            )\n',
    '\n',
    '        analyze_outputs = [\n',
    '            status,\n',
    '            audio_preview,\n',
    '            summary,\n',
    '            timeline,\n',
    '            player,\n',
    '            chart,\n',
    '            diagrams,\n',
    '            downloads,\n',
    '            state,\n',
    '            capo,\n',
    '        ]\n',
    '        analyze_button.click(\n',
    '            _analyze_ui,\n',
    '            [youtube_url, upload, detail, smoothing, meter_override, instrument],\n',
    '            analyze_outputs,\n',
    '            api_name="analyze",\n',
    '            concurrency_limit=1,\n',
    '        )\n',
    '        youtube_url.submit(\n',
    '            _analyze_ui,\n',
    '            [youtube_url, upload, detail, smoothing, meter_override, instrument],\n',
    '            analyze_outputs,\n',
    '            api_name=False,\n',
    '            concurrency_limit=1,\n',
    '        )\n',
    '        refresh_inputs = [timeline, state, transpose, capo, notation, instrument, meter_override]\n',
    '        refresh_outputs = [summary, player, chart, diagrams]\n',
    '        for component in (transpose, capo, notation, instrument, meter_override):\n',
    '            component.change(\n',
    '                _refresh_ui,\n',
    '                refresh_inputs,\n',
    '                refresh_outputs,\n',
    '                api_name=False,\n',
    '                trigger_mode="always_last",\n',
    '            )\n',
    '        apply_button.click(_refresh_ui, refresh_inputs, refresh_outputs, api_name="refresh")\n',
    '        quantize_button.click(_quantize_ui, [timeline, state], timeline, api_name="quantize")\n',
    '        merge_button.click(_merge_ui, timeline, timeline, api_name="merge")\n',
    '        export_button.click(\n',
    '            _export_ui,\n',
    '            refresh_inputs,\n',
    '            [status, summary, player, chart, diagrams, downloads],\n',
    '            api_name="export",\n',
    '        )\n',
    '        clear_button.add(\n',
    '            [\n',
    '                youtube_url,\n',
    '                upload,\n',
    '                status,\n',
    '                audio_preview,\n',
    '                summary,\n',
    '                timeline,\n',
    '                player,\n',
    '                chart,\n',
    '                diagrams,\n',
    '                downloads,\n',
    '                state,\n',
    '            ]\n',
    '        )\n',
    '    return demo\n',
    '\n',
    '\n',
    'def main() -> None:\n',
    '    demo = build_demo()\n',
    '    demo.queue(max_size=8, default_concurrency_limit=1)\n',
    '    workspace = default_workspace_root()\n',
    '    workspace.mkdir(parents=True, exist_ok=True)\n',
    '    demo.launch(\n',
    '        server_name=os.getenv("GRADIO_SERVER_NAME", "127.0.0.1"),\n',
    '        server_port=int(os.getenv("GRADIO_SERVER_PORT", "7860")),\n',
    '        show_error=True,\n',
    '        allowed_paths=[str(Path(workspace).resolve())],\n',
    '        max_file_size="600mb",\n',
    '        css=APP_CSS,\n',
    '    )\n',
    '\n',
    '\n',
    'if __name__ == "__main__":\n',
    '    main()\n',
], append=True)

put('tests/conftest.py', [
    'from __future__ import annotations\n',
    '\n',
    'import sys\n',
    'from pathlib import Path\n',
    '\n',
    'SRC = Path(__file__).resolve().parents[1] / "src"\n',
    'if str(SRC) not in sys.path:\n',
    '    sys.path.insert(0, str(SRC))\n',
], append=False)

put('tests/test_analyzer.py', [
    'from __future__ import annotations\n',
    '\n',
    'from pathlib import Path\n',
    '\n',
    'import numpy as np\n',
    'import pytest\n',
    'import soundfile as sf\n',
    '\n',
    'from sgchords.analyzer import AnalysisError, AnalyzerConfig, analyze_audio\n',
    'from sgchords.chords import simplify_chord\n',
    '\n',
    '\n',
    'def synth_chord(\n',
    '    root_midi: int, intervals: tuple[int, ...], seconds: float, sample_rate: int\n',
    ') -> np.ndarray:\n',
    '    time = np.arange(int(seconds * sample_rate)) / sample_rate\n',
    '    values = np.zeros_like(time)\n',
    '    for interval in intervals:\n',
    '        frequency = 440 * 2 ** ((root_midi + interval - 69) / 12)\n',
    '        for harmonic in range(1, 5):\n',
    '            values += np.sin(2 * np.pi * frequency * harmonic * time) / harmonic\n',
    '    bass = 440 * 2 ** ((root_midi - 12 - 69) / 12)\n',
    '    values += 1.1 * np.sin(2 * np.pi * bass * time)\n',
    '    values /= max(float(np.max(np.abs(values))), 1e-9)\n',
    '    fade = min(int(0.025 * sample_rate), len(values) // 4)\n',
    '    envelope = np.ones_like(values)\n',
    '    envelope[:fade] = np.linspace(0, 1, fade)\n',
    '    envelope[-fade:] = np.linspace(1, 0, fade)\n',
    '    return 0.34 * values * envelope\n',
    '\n',
    '\n',
    'def make_progression(sample_rate: int = 22_050) -> np.ndarray:\n',
    '    blocks = []\n',
    '    for root, intervals in [(48, (0, 4, 7)), (55, (0, 4, 7)), (57, (0, 3, 7)), (53, (0, 4, 7))]:\n',
    '        block = synth_chord(root, intervals, 2, sample_rate)\n',
    '        for offset in (0, 0.5, 1, 1.5):\n',
    '            start = int(offset * sample_rate)\n',
    '            block[start : start + 96] += np.hanning(96) * 0.08\n',
    '        blocks.append(block)\n',
    '    return np.concatenate(blocks)\n',
    '\n',
    '\n',
    'def chord_at(segments, timestamp: float) -> str:\n',
    '    for segment in segments:\n',
], append=False)
