from __future__ import annotations

from pathlib import Path


def put(path: str, lines: list[str], *, append: bool = False) -> None:
    target = Path(path)
    target.parent.mkdir(parents=True, exist_ok=True)
    mode = "a" if append else "w"
    with target.open(mode, encoding="utf-8", newline="") as handle:
        handle.writelines(lines)


put('src/sgchords/ui.py', [
    '            <button type="button" data-action="rate" data-rate="0.75">0.75×</button>\n',
], append=True)

put('src/sgchords/ui.py', [
    '            <button type="button" data-action="rate" data-rate="1" class="sg-on">1×</button>\n',
    '            <button type="button" data-action="rate" data-rate="1.25">1.25×</button>\n',
    '            <button type="button" data-action="forward">+5s</button>\n',
    '            <button type="button" data-action="loop">Loop selected chord</button>\n',
    '          </div>\n',
    '          <div class="sg-help">Click a chord to seek. Double-click one to select the practice loop.</div>\n',
    '          <div class="sg-strip">\n',
    '            ${value && value.segments && value.segments.length\n',
    '              ? value.segments.map((s,i)=>`<button type="button" class="sg-chord" data-segment="${i}" data-start="${s.start}" data-end="${s.end}"><span class="sg-time">${s.time}</span><strong>${s.display}</strong><span class="sg-secondary">${s.secondary||\'\'}</span><span class="sg-confidence">${Math.round(s.confidence*100)}%</span></button>`).join(\'\')\n',
    '              : \'<div class="sg-empty">The synchronized chord track will appear here.</div>\'}\n',
    '          </div>\n',
    '        </div>\n',
    '        """\n',
    '        css_template = r"""\n',
    '        .sg-sync-shell{border:1px solid var(--border-color-primary);border-radius:22px;padding:16px;background:var(--block-background-fill)}\n',
    '        .sg-now{display:grid;grid-template-columns:1.35fr .65fr;gap:14px;padding:16px;border-radius:18px;background:linear-gradient(135deg,rgba(101,116,255,.18),rgba(162,92,255,.11))}\n',
    '        .sg-kicker{font-size:.68rem;letter-spacing:.14em;font-weight:850;opacity:.6}.sg-current{font-size:clamp(3.2rem,8vw,6.8rem);line-height:.95;font-weight:900;letter-spacing:-.06em;margin-top:7px}.sg-meta{opacity:.72;margin-top:7px}.sg-next-wrap{text-align:right;align-self:end}.sg-next{font-size:clamp(1.7rem,4vw,3rem);font-weight:850}.sg-countdown{opacity:.68;font-variant-numeric:tabular-nums}\n',
    '        .sg-actions{display:flex;gap:8px;flex-wrap:wrap;margin:12px 0 7px}.sg-actions button{border:1px solid var(--border-color-primary);border-radius:999px;padding:7px 12px;background:transparent;color:inherit;cursor:pointer;font-weight:700}.sg-actions button.sg-on,.sg-actions button:hover{background:rgba(101,116,255,.18)}\n',
    '        .sg-help{font-size:.82rem;opacity:.65;margin-bottom:10px}.sg-strip{display:flex;gap:9px;overflow-x:auto;padding:4px 2px 9px;scroll-behavior:smooth}.sg-chord{min-width:116px;padding:10px 12px;border:1px solid var(--border-color-primary);border-radius:15px;background:transparent;color:inherit;text-align:left;cursor:pointer;transition:.15s}.sg-chord:hover{transform:translateY(-2px)}.sg-chord.sg-active{background:linear-gradient(135deg,rgba(101,116,255,.28),rgba(162,92,255,.22));border-color:#6574ff;box-shadow:0 10px 28px rgba(80,88,190,.17)}.sg-chord.sg-selected{outline:2px solid #a25cff;outline-offset:2px}.sg-chord span{display:block;font-size:.72rem;opacity:.64}.sg-chord strong{display:block;font-size:1.45rem;line-height:1.05;margin:4px 0}.sg-confidence{text-align:right}.sg-empty{padding:24px;opacity:.62}@media(max-width:720px){.sg-now{grid-template-columns:1fr}.sg-next-wrap{text-align:left}}\n',
    '        """\n',
    '        js_on_load = r"""\n',
    '        if(element.__sgCleanup) element.__sgCleanup();\n',
    '        let selected=null,loop=false,last=-1;\n',
    "        const audio=()=>document.querySelector('#sg-audio-player audio');\n",
    "        const cards=()=>Array.from(element.querySelectorAll('[data-segment]'));\n",
    '        const role=(name)=>element.querySelector(`[data-role="${name}"]`);\n',
    '        const indexAt=(time)=>{const list=cards();for(let i=0;i<list.length;i++){if(time>=Number(list[i].dataset.start)&&time<Number(list[i].dataset.end))return i;}return list.length?Math.max(0,list.length-1):-1;};\n',
    "        const render=(index,time)=>{const list=cards();list.forEach((card,i)=>card.classList.toggle('sg-active',i===index));if(index<0||!list[index])return;const current=list[index],next=list[index+1];role('current').textContent=current.querySelector('strong')?.textContent||'—';role('meta').textContent=current.querySelector('.sg-secondary')?.textContent||'Concert chord';role('next').textContent=next?.querySelector('strong')?.textContent||'—';const remaining=Math.max(0,Number(current.dataset.end)-time);role('countdown').textContent=next?`in ${remaining.toFixed(1)}s`:'final chord';if(index!==last){current.scrollIntoView({behavior:'smooth',inline:'center',block:'nearest'});last=index;}};\n",
    '        const tick=()=>{const player=audio();if(!player)return;const index=indexAt(player.currentTime||0);render(index,player.currentTime||0);if(loop&&selected!==null){const card=cards()[selected];if(card&&player.currentTime>=Number(card.dataset.end)-.025){player.currentTime=Number(card.dataset.start);if(player.paused)player.play().catch(()=>{});}}};\n',
    '        const click=(event)=>{const player=audio();const action=event.target.closest(\'[data-action]\');if(action&&player){if(action.dataset.action===\'back\')player.currentTime=Math.max(0,player.currentTime-5);if(action.dataset.action===\'forward\')player.currentTime=Math.min(player.duration||Infinity,player.currentTime+5);if(action.dataset.action===\'rate\'){player.playbackRate=Number(action.dataset.rate||1);element.querySelectorAll(\'[data-action="rate"]\').forEach(button=>button.classList.toggle(\'sg-on\',button===action));}if(action.dataset.action===\'loop\'){loop=!loop;action.classList.toggle(\'sg-on\',loop);}return;}const card=event.target.closest(\'[data-segment]\');if(card&&player){player.currentTime=Number(card.dataset.start);player.play().catch(()=>{});}};\n',
    "        const dbl=(event)=>{const card=event.target.closest('[data-segment]');if(!card)return;selected=Number(card.dataset.segment);cards().forEach((item,i)=>item.classList.toggle('sg-selected',i===selected));};\n",
    "        element.addEventListener('click',click);element.addEventListener('dblclick',dbl);const timer=setInterval(tick,100);element.__sgCleanup=()=>{clearInterval(timer);element.removeEventListener('click',click);element.removeEventListener('dblclick',dbl);};\n",
    '        """\n',
    '        super().__init__(\n',
    '            value=value or {"segments": []},\n',
    '            html_template=html_template,\n',
    '            css_template=css_template,\n',
    '            js_on_load=js_on_load,\n',
    '            **kwargs,\n',
    '        )\n',
    '\n',
    '    def api_info(self) -> dict[str, Any]:\n',
    '        return {"type": "object"}\n',
    '\n',
    '\n',
    'def _timeline_frame(segments: list[ChordSegment]) -> pd.DataFrame:\n',
    '    return pd.DataFrame([segment.to_row() for segment in segments], columns=HEADERS)\n',
    '\n',
    '\n',
    'def _meter(value: str | int | None) -> int | None:\n',
    '    return int(value) if value in {3, 4, 6, "3", "4", "6"} else None\n',
    '\n',
    '\n',
    'def _views(\n',
    '    result: AnalysisResult,\n',
    '    segments: list[ChordSegment],\n',
    '    *,\n',
    '    transpose: int,\n',
    '    capo: int,\n',
    '    notation: str,\n',
    '    instrument: str,\n',
    '    meter_override: int | None,\n',
    ') -> tuple[str, dict[str, Any], str, str]:\n',
    '    target_key = transpose_key(result.key, transpose)\n',
    '    flats = key_prefers_flats(target_key)\n',
    '    sounding = transpose_segments(segments, transpose, prefer_flats=flats)\n',
    '    shape_key = transpose_key(target_key, -capo) if capo else target_key\n',
    '    shapes = capo_shape_segments(sounding, capo, prefer_flats=key_prefers_flats(shape_key))\n',
    '    payload: list[dict[str, Any]] = []\n',
    '    for sound, shape in zip(sounding, shapes, strict=True):\n',
    '        local_key = transpose_key(sound.local_key, transpose) if sound.local_key else target_key\n',
    '        display = (\n',
    '            shape.chord\n',
    '            if notation == "standard"\n',
    '            else format_chord_notation(sound.chord, local_key, notation)\n',
    '        )\n',
    '        secondary: list[str] = []\n',
    '        if capo and notation == "standard":\n',
    '            secondary.append(f"sounds {sound.chord}")\n',
    '        if sound.local_key:\n',
    '            secondary.append(local_key)\n',
    '        if sound.bar is not None:\n',
    '            secondary.append(\n',
    '                f"bar {sound.bar}" + (f", beat {sound.beat:.1f}" if sound.beat is not None else "")\n',
    '            )\n',
    '        minutes, seconds = divmod(sound.start, 60)\n',
    '        payload.append(\n',
    '            {\n',
    '                "start": round(sound.start, 4),\n',
    '                "end": round(sound.end, 4),\n',
    '                "time": f"{int(minutes):02d}:{seconds:04.1f}",\n',
    '                "display": display,\n',
    '                "secondary": " · ".join(secondary),\n',
    '                "confidence": sound.confidence,\n',
    '            }\n',
    '        )\n',
    '    return (\n',
    '        render_summary(result, segments, transpose=transpose, instrument=instrument, capo=capo),\n',
    '        {"segments": payload},\n',
    '        render_bar_chart(\n',
    '            result,\n',
    '            segments,\n',
    '            transpose=transpose,\n',
    '            capo=capo,\n',
    '            notation=notation,\n',
    '            meter_override=meter_override,\n',
    '        ),\n',
    '        render_chord_diagrams_html((segment.chord for segment in shapes), instrument),\n',
    '    )\n',
    '\n',
    '\n',
    'def _analyze_ui(\n',
    '    youtube_url: str,\n',
    '    upload_path: str | None,\n',
    '    detail: str,\n',
    '    smoothing: float,\n',
    '    meter_override: str,\n',
    '    instrument: str,\n',
    '    progress: gr.Progress = PROGRESS,\n',
    ') -> tuple[str, str, str, pd.DataFrame, dict[str, Any], str, str, list[str], dict[str, Any], int]:\n',
    '    try:\n',
    '        progress(0.04, desc="Preparing audio")\n',
    '        result, job_dir = analyze_request(\n',
    '            youtube_url=youtube_url,\n',
    '            upload_path=upload_path,\n',
    '            detail=detail,\n',
    '            smoothing=float(smoothing),\n',
    '            meter_override=_meter(meter_override),\n',
    '        )\n',
    '        progress(0.88, desc="Building synchronized chart")\n',
    '        capo, _shapes, _ease = suggest_capo(result.segments, instrument)\n',
    '        summary, player, chart, diagrams = _views(\n',
    '            result,\n',
    '            result.segments,\n',
    '            transpose=0,\n',
    '            capo=capo,\n',
    '            notation="standard",\n',
    '            instrument=instrument,\n',
    '            meter_override=_meter(meter_override),\n',
    '        )\n',
    '        files = write_exports(\n',
    '            result,\n',
    '            job_dir / "exports",\n',
    '            instrument=instrument,\n',
    '            capo=capo,\n',
    '            meter_override=_meter(meter_override),\n',
    '        )\n',
    '        progress(1.0, desc="Done")\n',
    '        return (\n',
    '            "Analysis complete. The chord strip follows playback. Edit anything that sounds wrong, then apply edits or regenerate downloads.",\n',
    '            result.audio_path,\n',
    '            summary,\n',
    '            _timeline_frame(result.segments),\n',
    '            player,\n',
    '            chart,\n',
    '            diagrams,\n',
    '            files,\n',
    '            result.to_state(),\n',
    '            capo,\n',
    '        )\n',
    '    except Exception as exc:\n',
    '        raise gr.Error(str(exc)) from exc\n',
    '\n',
    '\n',
    'def _refresh_ui(\n',
    '    timeline: Any,\n',
    '    state: dict[str, Any],\n',
    '    transpose: int,\n',
    '    capo: int,\n',
    '    notation: str,\n',
    '    instrument: str,\n',
    '    meter_override: str,\n',
    ') -> tuple[str, dict[str, Any], str, str]:\n',
    '    try:\n',
    '        if not state:\n',
    '            return "Analyze a song first.", {"segments": []}, "", ""\n',
    '        return _views(\n',
    '            AnalysisResult.from_state(state),\n',
    '            rows_to_segments(timeline),\n',
    '            transpose=int(transpose),\n',
    '            capo=int(capo),\n',
    '            notation=notation,\n',
    '            instrument=instrument,\n',
    '            meter_override=_meter(meter_override),\n',
    '        )\n',
    '    except Exception as exc:\n',
    '        raise gr.Error(str(exc)) from exc\n',
    '\n',
    '\n',
    'def _export_ui(\n',
    '    timeline: Any,\n',
    '    state: dict[str, Any],\n',
    '    transpose: int,\n',
    '    capo: int,\n',
    '    notation: str,\n',
    '    instrument: str,\n',
    '    meter_override: str,\n',
    ') -> tuple[str, str, dict[str, Any], str, str, list[str]]:\n',
    '    try:\n',
    '        result, files = export_from_state(\n',
    '            state,\n',
    '            timeline,\n',
    '            transpose=int(transpose),\n',
    '            instrument=instrument,\n',
    '            capo=int(capo),\n',
    '            notation=notation,\n',
    '            meter_override=_meter(meter_override),\n',
    '        )\n',
], append=True)
