from __future__ import annotations

from pathlib import Path


def put(path: str, lines: list[str], *, append: bool = False) -> None:
    target = Path(path)
    target.parent.mkdir(parents=True, exist_ok=True)
    mode = "a" if append else "w"
    with target.open(mode, encoding="utf-8", newline="") as handle:
        handle.writelines(lines)


put('benchmarks/README.md', [
    '| C major I–IV–V–I | `C → F → G → C` | Literal-pitch sequence and vocabulary |\n',
], append=True)

put('benchmarks/README.md', [
    '| C major I–IV–V–I–I–V–I | `C → F → G → C → C → G → C` | Literal-pitch sequence and vocabulary |\n',
    '| I–V–vi–IV resolving to I | `C → G → Am → F → C` | Literal-pitch sequence and vocabulary; inversions reduced to roots |\n',
    '| La Bamba guitar clip | `C → F → G7` | Literal-pitch order and vocabulary |\n',
    '| Hotaru no Hikari / Auld Lang Syne | Published four-line progression | Sequence and vocabulary with one permitted global transposition, because guitar chord names can be capo-relative |\n',
    '\n',
    'Run it with uv:\n',
    '\n',
    '```bash\n',
    'uv sync --locked\n',
    'uv run --frozen python scripts/benchmark_known_chords.py --output benchmark-results\n',
    '```\n',
    '\n',
    'The audio files are downloaded into a temporary directory and never committed. Generated output contains:\n',
    '\n',
    '- `results.md`: readable report\n',
    '- `results.json`: structured metrics and analyzer metadata\n',
    '- `timelines/*.csv`: every detected segment with confidence, local key, bar, and beat\n',
    '\n',
    '## What the score means\n',
    '\n',
    'Adjacent duplicate labels are collapsed, then the detected sequence is compared with the reference using longest-common-subsequence matching. Sequence recall asks how much of the expected order appeared. Sequence precision penalizes excessive extra changes. Vocabulary recall ignores timing and asks whether the expected chord types appeared at all.\n',
    '\n',
    'This is deliberately stricter than reporting only chord-set coverage, but it still does not validate exact boundary timestamps because the source recordings do not publish frame-accurate annotations.\n',
], append=True)

put('scripts/benchmark_known_chords.py', [
    'from __future__ import annotations\n',
    '\n',
    'import argparse\n',
    'import csv\n',
    'import json\n',
    'import shutil\n',
    'import tempfile\n',
    'import time\n',
    'import urllib.error\n',
    'import urllib.request\n',
    'from collections.abc import Sequence\n',
    'from dataclasses import asdict, dataclass\n',
    'from pathlib import Path\n',
    'from typing import Any\n',
    '\n',
    'from sgchords.analyzer import analyze_audio\n',
    'from sgchords.audio import prepare_local_audio\n',
    'from sgchords.chords import parse_chord, pitch_name, transpose_chord\n',
    'from sgchords.models import ChordSegment\n',
    '\n',
    'USER_AGENT = "SgChords known-chord benchmark/0.2 (+https://github.com/Legedith/Sgchords)"\n',
    '\n',
    '\n',
    '@dataclass(frozen=True, slots=True)\n',
    'class BenchmarkSong:\n',
    '    slug: str\n',
    '    title: str\n',
    '    file_url: str\n',
    '    source_page: str\n',
    '    license_note: str\n',
    '    expected_sequence: tuple[str, ...]\n',
    '    evaluation_note: str\n',
    '    allow_global_transposition: bool = False\n',
    '    detail: str = "standard"\n',
    '    smoothing: float = 0.68\n',
    '\n',
    '\n',
    'SONGS = (\n',
    '    BenchmarkSong(\n',
    '        slug="c-major-i-iv-v-i",\n',
    '        title="C major I–IV–V–I",\n',
    '        file_url=(\n',
    '            "https://upload.wikimedia.org/wikipedia/commons/5/5a/"\n',
    '            "C_major%2C_Middle_C%2C_I-IV-V-I_chord_progression.ogg"\n',
    '        ),\n',
    '        source_page=(\n',
    '            "https://commons.wikimedia.org/wiki/"\n',
    '            "File:C_major,_Middle_C,_I-IV-V-I_chord_progression.ogg"\n',
    '        ),\n',
    '        license_note="CC0 / public-domain dedication.",\n',
    '        expected_sequence=("C", "F", "G", "C"),\n',
    '        evaluation_note="Exact piano progression named by the source; literal pitch is scored.",\n',
    '    ),\n',
    '    BenchmarkSong(\n',
    '        slug="c-major-i-iv-v-i-i-v-i",\n',
    '        title="C major I–IV–V–I–I–V–I",\n',
    '        file_url=(\n',
    '            "https://upload.wikimedia.org/wikipedia/commons/b/bc/"\n',
    '            "C_major%2C_Middle_C%2C_I-IV-V-I-I-V-I_chord_progression.ogg"\n',
    '        ),\n',
    '        source_page=(\n',
    '            "https://commons.wikimedia.org/wiki/"\n',
    '            "File:C_major,_Middle_C,_I-IV-V-I-I-V-I_chord_progression.ogg"\n',
    '        ),\n',
    '        license_note="CC0 / public-domain dedication.",\n',
    '        expected_sequence=("C", "F", "G", "C", "C", "G", "C"),\n',
    '        evaluation_note="Exact piano progression named by the source; literal pitch is scored.",\n',
    '    ),\n',
    '    BenchmarkSong(\n',
    '        slug="i-v-vi-iv-in-c",\n',
    '        title="I–V–vi–IV resolving to I in C",\n',
    '        file_url=(\n',
    '            "https://upload.wikimedia.org/wikipedia/commons/f/f7/"\n',
    '            "I-V-vi-IV_chord_progression_in_C.oga"\n',
    '        ),\n',
    '        source_page=(\n',
    '            "https://commons.wikimedia.org/wiki/File:I-V-vi-IV_chord_progression_in_C.oga"\n',
    '        ),\n',
    '        license_note="CC BY-SA 3.0 / GFDL.",\n',
    '        expected_sequence=("C", "G", "Am", "F", "C"),\n',
    '        evaluation_note=(\n',
    '            "The source states I–V–vi–IV resolving to I; inversions are reduced to chord roots."\n',
    '        ),\n',
    '    ),\n',
    '    BenchmarkSong(\n',
    '        slug="la-bamba-c-f-g7",\n',
    '        title="La Bamba guitar chords C–F–G7",\n',
    '        file_url=("https://upload.wikimedia.org/wikipedia/commons/6/63/La_bamba_chords_cfg7.ogg"),\n',
    '        source_page=("https://commons.wikimedia.org/wiki/File:La_bamba_chords_cfg7.ogg"),\n',
    '        license_note="CC BY-SA 4.0.",\n',
    '        expected_sequence=("C", "F", "G7"),\n',
    '        evaluation_note=(\n',
    '            "The source states the played guitar chords C–F–G7; order and vocabulary are scored."\n',
    '        ),\n',
    '    ),\n',
    '    BenchmarkSong(\n',
    '        slug="hotaru-no-hikari",\n',
    '        title="Hotaru no Hikari / Auld Lang Syne",\n',
    '        file_url=(\n',
    '            "https://upload.wikimedia.org/wikipedia/commons/f/f4/"\n',
    '            "Hotaru_no_Hikari%28Auld_lang_syne_in_Japan%29.ogg"\n',
    '        ),\n',
    '        source_page=(\n',
    '            "https://commons.wikimedia.org/wiki/File:Hotaru_no_Hikari(Auld_lang_syne_in_Japan).ogg"\n',
    '        ),\n',
    '        license_note="Public-domain dedication by the performer.",\n',
    '        expected_sequence=(\n',
    '            "C",\n',
    '            "G",\n',
    '            "Am",\n',
    '            "F",\n',
    '            "C",\n',
    '            "G",\n',
    '            "F",\n',
    '            "G",\n',
    '            "C",\n',
    '            "C",\n',
    '            "G",\n',
    '            "C/G",\n',
    '            "F",\n',
    '            "C",\n',
    '            "G",\n',
    '            "F",\n',
    '            "G",\n',
    '            "C",\n',
    '        ),\n',
    '        evaluation_note=(\n',
    '            "Guitar and vocal. One global transposition is allowed because published guitar "\n',
    '            "shapes can be capo-relative; timing is not source-annotated."\n',
    '        ),\n',
    '        allow_global_transposition=True,\n',
    '    ),\n',
    ')\n',
    '\n',
    '\n',
    'def download(url: str, destination: Path, *, attempts: int = 4) -> None:\n',
    '    destination.parent.mkdir(parents=True, exist_ok=True)\n',
    '    last_error: Exception | None = None\n',
    '    for attempt in range(1, attempts + 1):\n',
    '        request = urllib.request.Request(url, headers={"User-Agent": USER_AGENT})\n',
    '        try:\n',
    '            with (\n',
    '                urllib.request.urlopen(request, timeout=90) as response,\n',
    '                destination.open("wb") as output,\n',
    '            ):\n',
    '                shutil.copyfileobj(response, output)\n',
    '            if destination.stat().st_size < 1_000:\n',
    '                raise RuntimeError("downloaded file is unexpectedly small")\n',
    '            return\n',
    '        except (OSError, RuntimeError, urllib.error.URLError) as exc:\n',
    '            last_error = exc\n',
    '            destination.unlink(missing_ok=True)\n',
    '            if attempt < attempts:\n',
    '                time.sleep(2**attempt)\n',
    '    raise RuntimeError(f"Could not download {url}: {last_error}")\n',
    '\n',
    '\n',
    'def _quality_family(chord: str) -> str:\n',
    '    parsed = parse_chord(chord)\n',
    '    if parsed is None:\n',
    '        return "N" if chord.strip().upper() in {"N", "NC", "N.C."} else chord\n',
    '    root, suffix = parsed\n',
    '    lower = suffix.lower().split("/", 1)[0]\n',
    '    if lower.startswith("maj"):\n',
    '        quality = ""\n',
    '    elif lower.startswith("m"):\n',
    '        quality = "m"\n',
    '    elif lower.startswith("7"):\n',
    '        quality = "7"\n',
    '    elif lower.startswith("dim"):\n',
    '        quality = "dim"\n',
    '    else:\n',
    '        quality = ""\n',
    '    return f"{pitch_name(root, 'b' in chord[:2])}{quality}"\n',
    '\n',
    '\n',
    'def collapse_sequence(segments: Sequence[ChordSegment]) -> list[str]:\n',
    '    sequence: list[str] = []\n',
    '    for segment in segments:\n',
    '        chord = _quality_family(segment.chord)\n',
    '        if chord == "N":\n',
    '            continue\n',
    '        if not sequence or sequence[-1] != chord:\n',
    '            sequence.append(chord)\n',
    '    return sequence\n',
    '\n',
    '\n',
    'def lcs_length(left: Sequence[str], right: Sequence[str]) -> int:\n',
    '    previous = [0] * (len(right) + 1)\n',
    '    for left_item in left:\n',
    '        current = [0]\n',
    '        for index, right_item in enumerate(right, start=1):\n',
    '            if left_item == right_item:\n',
    '                current.append(previous[index - 1] + 1)\n',
    '            else:\n',
    '                current.append(max(previous[index], current[-1]))\n',
    '        previous = current\n',
    '    return previous[-1]\n',
    '\n',
    '\n',
    'def _signed_shift(value: int) -> int:\n',
    '    value %= 12\n',
    '    return value if value <= 6 else value - 12\n',
    '\n',
    '\n',
    'def _transpose_reference(sequence: Sequence[str], semitones: int) -> list[str]:\n',
    '    return [_quality_family(transpose_chord(chord, semitones)) for chord in sequence]\n',
    '\n',
    '\n',
    'def score_sequence(\n',
    '    expected: Sequence[str],\n',
    '    detected: Sequence[str],\n',
    '    *,\n',
    '    allow_global_transposition: bool,\n',
    ') -> dict[str, Any]:\n',
    '    shifts = range(12) if allow_global_transposition else (0,)\n',
    '    candidates: list[tuple[float, float, float, int, list[str]]] = []\n',
    '    detected_list = list(detected)\n',
    '    for raw_shift in shifts:\n',
    '        shifted = _transpose_reference(expected, raw_shift)\n',
    '        match = lcs_length(shifted, detected_list)\n',
    '        recall = match / max(len(shifted), 1)\n',
    '        precision = match / max(len(detected_list), 1)\n',
    '        f1 = 0.0 if recall + precision == 0 else 2 * recall * precision / (recall + precision)\n',
    '        candidates.append((f1, recall, precision, raw_shift, shifted))\n',
    '    best = max(\n',
    '        candidates,\n',
    '        key=lambda item: (item[0], item[1], item[2], -abs(_signed_shift(item[3]))),\n',
    '    )\n',
    '    shifted = best[4]\n',
    '    expected_vocab = set(shifted)\n',
    '    detected_vocab = set(detected_list)\n',
    '    overlap = expected_vocab & detected_vocab\n',
    '    vocabulary_recall = len(overlap) / max(len(expected_vocab), 1)\n',
    '    vocabulary_precision = len(overlap) / max(len(detected_vocab), 1)\n',
    '    return {\n',
    '        "shift_semitones": _signed_shift(best[3]),\n',
    '        "aligned_expected": shifted,\n',
    '        "lcs_matches": lcs_length(shifted, detected_list),\n',
    '        "sequence_recall": round(best[1], 4),\n',
    '        "sequence_precision": round(best[2], 4),\n',
    '        "sequence_f1": round(best[0], 4),\n',
    '        "vocabulary_recall": round(vocabulary_recall, 4),\n',
    '        "vocabulary_precision": round(vocabulary_precision, 4),\n',
    '        "missing_vocabulary": sorted(expected_vocab - detected_vocab),\n',
    '        "extra_vocabulary": sorted(detected_vocab - expected_vocab),\n',
    '    }\n',
    '\n',
    '\n',
    'def duration_weighted_confidence(segments: Sequence[ChordSegment]) -> float:\n',
    '    sounding = [segment for segment in segments if segment.chord != "N"]\n',
    '    total = sum(segment.duration for segment in sounding)\n',
    '    if total <= 0:\n',
    '        return 0.0\n',
    '    return sum(segment.confidence * segment.duration for segment in sounding) / total\n',
    '\n',
    '\n',
    'def write_timeline(path: Path, segments: Sequence[ChordSegment]) -> None:\n',
    '    path.parent.mkdir(parents=True, exist_ok=True)\n',
    '    with path.open("w", newline="", encoding="utf-8") as handle:\n',
    '        writer = csv.writer(handle)\n',
    '        writer.writerow(\n',
    '            [\n',
    '                "start_seconds",\n',
    '                "end_seconds",\n',
    '                "chord",\n',
    '                "confidence",\n',
], append=False)
