from __future__ import annotations

from pathlib import Path


def put(path: str, lines: list[str], *, append: bool = False) -> None:
    target = Path(path)
    target.parent.mkdir(parents=True, exist_ok=True)
    mode = "a" if append else "w"
    with target.open(mode, encoding="utf-8", newline="") as handle:
        handle.writelines(lines)


put('src/sgchords/exports.py', [
    '    sounding = transpose_segments(segments, transpose, prefer_flats=flats)\n',
], append=True)

put('src/sgchords/exports.py', [
    '    shape_key = transpose_key(target_key, -capo) if capo else target_key\n',
    '    shapes = capo_shape_segments(sounding, capo, prefer_flats=key_prefers_flats(shape_key))\n',
    '    meter = meter_override if meter_override in {3, 4, 6} else result.meter\n',
    '    header = (\n',
    '        f"{result.title}\\nKey: {target_key} | Tempo: "\n',
    '        + ("unknown" if result.tempo_bpm is None else f"{result.tempo_bpm:.1f} BPM")\n',
    '        + f" | Meter: {meter}/4 | Transpose: {transpose:+d}"\n',
    '        + (f" | Capo {capo} (shape names)" if capo else "")\n',
    '        + "\\n"\n',
    '    )\n',
    '    if not shapes:\n',
    '        return header + "\\nNo chord segments."\n',
    '    if len(result.beats) < 2:\n',
    '        entries = []\n',
    '        for sound, shape in zip(sounding, shapes, strict=True):\n',
    '            label = (\n',
    '                shape.chord\n',
    '                if notation == "standard"\n',
    '                else format_chord_notation(sound.chord, target_key, notation)\n',
    '            )\n',
    '            entries.append(f"[{format_timestamp(sound.start)}] {label}")\n',
    '        return (\n',
    '            header\n',
    '            + "\\n"\n',
    '            + "\\n".join(\n',
    '                "    ".join(entries[index : index + 4]) for index in range(0, len(entries), 4)\n',
    '            )\n',
    '        )\n',
    '\n',
    '    beats = result.beats\n',
    '    rows: dict[int, list[str]] = defaultdict(list)\n',
    '    for beat in beats:\n',
    '        if beat.time >= sounding[-1].end:\n',
    '            continue\n',
    '        sound = _chord_at_time(sounding, beat.time)\n',
    '        shape = _chord_at_time(shapes, beat.time)\n',
    '        if sound is None or shape is None:\n',
    '            label = "N"\n',
    '        elif notation == "standard":\n',
    '            label = shape.chord\n',
    '        else:\n',
    '            local_key = transpose_key(sound.local_key, transpose) if sound.local_key else target_key\n',
    '            label = format_chord_notation(sound.chord, local_key, notation)\n',
    '        rows[beat.bar].append(label)\n',
    '    lines = [header.rstrip(), ""]\n',
    '    previous: str | None = None\n',
    '    for bar in sorted(rows):\n',
    '        cells = rows[bar][:meter]\n',
    '        cells.extend([cells[-1] if cells else "N"] * (meter - len(cells)))\n',
    '        display: list[str] = []\n',
    '        for chord in cells:\n',
    '            display.append("·" if chord == previous else chord)\n',
    '            previous = chord\n',
    '        lines.append(f"{bar:>3} | " + "  ".join(f"{cell:<8}" for cell in display).rstrip())\n',
    '    return "\\n".join(lines)\n',
    '\n',
    '\n',
    'def render_summary(\n',
    '    result: AnalysisResult,\n',
    '    segments: Sequence[ChordSegment],\n',
    '    *,\n',
    '    transpose: int = 0,\n',
    '    instrument: str = "guitar",\n',
    '    capo: int = 0,\n',
    ') -> str:\n',
    '    target_key = transpose_key(result.key, transpose)\n',
    '    sounding = [segment for segment in segments if segment.chord != "N"]\n',
    '    confidence = (\n',
    '        sum(segment.confidence * segment.duration for segment in sounding)\n',
    '        / max(sum(segment.duration for segment in sounding), 1e-9)\n',
    '        if sounding\n',
    '        else 0.0\n',
    '    )\n',
    '    suggested, suggested_shapes, ease = suggest_capo(sounding, instrument)\n',
    '    capo_message = f"capo {capo}" if capo else "no capo"\n',
    '    if capo == 0 and suggested:\n',
    '        capo_message += f"; automatic suggestion: capo {suggested} ({\', \'.join(suggested_shapes)})"\n',
    '    regions = (\n',
    '        ", ".join(\n',
    '            f"{format_timestamp(region.start)}–{format_timestamp(region.end)} {transpose_key(region.key, transpose)} ({region.confidence:.0%})"\n',
    '            for region in result.key_regions[:6]\n',
    '        )\n',
    '        or "no stable tonal regions"\n',
    '    )\n',
    '    tempo = (\n',
    '        "not stable"\n',
    '        if result.tempo_bpm is None\n',
    '        else f"{result.tempo_bpm:.1f} BPM ({result.tempo_confidence:.0%})"\n',
    '    )\n',
    '    lines = [\n',
    '        f"### {result.title}",\n',
    '        f"**Dominant tonal region:** {target_key} ({result.key_confidence:.0%})  ",\n',
    '        f"**Tempo / meter:** {tempo}; {result.meter}/4 ({result.meter_confidence:.0%} meter confidence)  ",\n',
    '        f"**Tuning:** {result.tuning_cents:+.0f} cents from A=440  ",\n',
    '        f"**Mean chord confidence:** {confidence:.0%}  ",\n',
    '        f"**{instrument.title()} setup:** {capo_message}; ease score {ease:.0%}  ",\n',
    '        f"**Local tonal map:** {regions}",\n',
    '    ]\n',
    '    if result.drone:\n',
    '        lines.append(\n',
    '            f"  \\n**Sustained tonal centre:** {result.drone} ({result.drone_confidence:.0%})"\n',
    '        )\n',
    '    if result.patterns:\n',
    '        pattern = result.patterns[0]\n',
    '        lines.append(\n',
    '            f"  \\n**Repeated pattern:** {\' → \'.join(pattern.chords)} ({pattern.occurrences} occurrences)"\n',
    '        )\n',
    '    if result.warnings:\n',
    '        lines.extend(["", "**Check by ear:**", *[f"- {warning}" for warning in result.warnings]])\n',
    '    return "\\n".join(lines)\n',
    '\n',
    '\n',
    'def render_shapes_for_segments(segments: Sequence[ChordSegment], instrument: str) -> str:\n',
    '    return render_chord_shapes((segment.chord for segment in segments), instrument)\n',
    '\n',
    '\n',
    'def _write_csv(path: Path, segments: Sequence[ChordSegment]) -> None:\n',
    '    with path.open("w", newline="", encoding="utf-8") as handle:\n',
    '        writer = csv.writer(handle)\n',
    '        writer.writerow(\n',
    '            ["start_seconds", "end_seconds", "chord", "confidence", "local_key", "bar", "beat"]\n',
    '        )\n',
    '        for segment in segments:\n',
    '            writer.writerow(\n',
    '                [\n',
    '                    f"{segment.start:.3f}",\n',
    '                    f"{segment.end:.3f}",\n',
    '                    segment.chord,\n',
    '                    f"{segment.confidence:.3f}",\n',
    '                    segment.local_key or "",\n',
    '                    segment.bar or "",\n',
    '                    "" if segment.beat is None else f"{segment.beat:.2f}",\n',
    '                ]\n',
    '            )\n',
    '\n',
    '\n',
    'def _write_chordpro(\n',
    '    path: Path, result: AnalysisResult, segments: Sequence[ChordSegment], key: str, capo: int\n',
    ') -> None:\n',
    '    lines = [f"{{title: {result.title}}}", f"{{key: {key}}}"]\n',
    '    if result.tempo_bpm is not None:\n',
    '        lines.append(f"{{tempo: {result.tempo_bpm:.0f}}}")\n',
    '    if capo:\n',
    '        lines.append(f"{{capo: {capo}}}")\n',
    '    lines.extend(["{comment: Automatic estimate; verify low-confidence changes by ear.}", ""])\n',
    '    for segment in segments:\n',
    '        lines.append(\n',
    '            f"{{comment: {format_timestamp(segment.start)}–{format_timestamp(segment.end)}}} [{segment.chord}]"\n',
    '        )\n',
    '    path.write_text("\\n".join(lines) + "\\n", encoding="utf-8")\n',
    '\n',
    '\n',
    'def _write_srt(path: Path, segments: Sequence[ChordSegment]) -> None:\n',
    '    blocks = [\n',
    '        f"{index}\\n{format_timestamp(segment.start, milliseconds=True)} --> {format_timestamp(segment.end, milliseconds=True)}\\n{segment.chord}\\n"\n',
    '        for index, segment in enumerate(segments, start=1)\n',
    '    ]\n',
    '    path.write_text("\\n".join(blocks), encoding="utf-8")\n',
    '\n',
    '\n',
    'def _write_lab(path: Path, segments: Sequence[ChordSegment]) -> None:\n',
    '    path.write_text(\n',
    '        "".join(\n',
    '            f"{segment.start:.3f}\\t{segment.end:.3f}\\t{segment.chord}\\n" for segment in segments\n',
    '        ),\n',
    '        encoding="utf-8",\n',
    '    )\n',
    '\n',
    '\n',
    'def write_exports(\n',
    '    result: AnalysisResult,\n',
    '    output_dir: str | Path,\n',
    '    *,\n',
    '    segments: Sequence[ChordSegment] | None = None,\n',
    '    transpose: int = 0,\n',
    '    instrument: str = "guitar",\n',
    '    capo: int = 0,\n',
    '    notation: str = "standard",\n',
    '    meter_override: int | None = None,\n',
    ') -> list[str]:\n',
    '    output = Path(output_dir)\n',
    '    output.mkdir(parents=True, exist_ok=True)\n',
    '    source = list(segments if segments is not None else result.segments)\n',
    '    key = transpose_key(result.key, transpose)\n',
    '    flats = key_prefers_flats(key)\n',
    '    concert = transpose_segments(source, transpose, prefer_flats=flats)\n',
    '    shape_key = transpose_key(key, -capo) if capo else key\n',
    '    displayed = capo_shape_segments(concert, capo, prefer_flats=key_prefers_flats(shape_key))\n',
    '    base = safe_filename(result.title)\n',
    '    paths = {\n',
    '        "text": output / f"{base}-chords.txt",\n',
    '        "csv": output / f"{base}-timeline.csv",\n',
    '        "json": output / f"{base}-analysis.json",\n',
    '        "chordpro": output / f"{base}.cho",\n',
    '        "shapes": output / f"{base}-{instrument}-shapes.txt",\n',
    '        "srt": output / f"{base}.srt",\n',
    '        "lab": output / f"{base}.lab",\n',
    '    }\n',
    '    paths["text"].write_text(\n',
    '        render_bar_chart(\n',
    '            result,\n',
    '            source,\n',
    '            transpose=transpose,\n',
    '            capo=capo,\n',
    '            notation=notation,\n',
    '            meter_override=meter_override,\n',
    '        )\n',
    '        + "\\n",\n',
    '        encoding="utf-8",\n',
    '    )\n',
    '    _write_csv(paths["csv"], concert)\n',
    '    payload = result.to_state()\n',
    '    payload.update(\n',
    '        {\n',
    '            "key": key,\n',
    '            "transpose": transpose,\n',
    '            "capo": capo,\n',
    '            "instrument": instrument,\n',
    '            "notation": notation,\n',
    '            "displayed_segments": [asdict(item) for item in displayed],\n',
    '            "segments": [asdict(item) for item in concert],\n',
    '        }\n',
    '    )\n',
    '    paths["json"].write_text(\n',
    '        json.dumps(payload, ensure_ascii=False, indent=2) + "\\n", encoding="utf-8"\n',
    '    )\n',
    '    _write_chordpro(paths["chordpro"], result, displayed, key, capo)\n',
    '    paths["shapes"].write_text(\n',
    '        render_shapes_for_segments(displayed, instrument) + "\\n", encoding="utf-8"\n',
    '    )\n',
    '    _write_srt(paths["srt"], concert)\n',
    '    _write_lab(paths["lab"], concert)\n',
    '    return [str(path) for path in paths.values()]\n',
], append=True)

put('src/sgchords/models.py', [
    'from __future__ import annotations\n',
    '\n',
    'from dataclasses import asdict, dataclass, field\n',
    'from typing import Any\n',
    '\n',
    '\n',
    '@dataclass(slots=True)\n',
    'class BeatPoint:\n',
    '    time: float\n',
    '    index: int\n',
    '    bar: int\n',
    '    beat: float\n',
    '    strength: float = 0.0\n',
    '    downbeat: bool = False\n',
    '\n',
    '    @classmethod\n',
    '    def from_dict(cls, value: dict[str, Any]) -> BeatPoint:\n',
    '        return cls(\n',
    '            time=float(value["time"]),\n',
    '            index=int(value.get("index", 0)),\n',
    '            bar=int(value.get("bar", 1)),\n',
    '            beat=float(value.get("beat", 1.0)),\n',
    '            strength=float(value.get("strength", 0.0)),\n',
    '            downbeat=bool(value.get("downbeat", False)),\n',
    '        )\n',
    '\n',
    '\n',
    '@dataclass(slots=True)\n',
    'class KeyRegion:\n',
    '    start: float\n',
    '    end: float\n',
    '    key: str\n',
    '    confidence: float\n',
    '    root: int\n',
    '    mode: str\n',
    '\n',
    '    @property\n',
    '    def duration(self) -> float:\n',
    '        return max(0.0, self.end - self.start)\n',
    '\n',
    '    @classmethod\n',
    '    def from_dict(cls, value: dict[str, Any]) -> KeyRegion:\n',
    '        return cls(\n',
    '            start=float(value["start"]),\n',
    '            end=float(value["end"]),\n',
    '            key=str(value["key"]),\n',
    '            confidence=float(value.get("confidence", 0.0)),\n',
    '            root=int(value.get("root", 0)),\n',
    '            mode=str(value.get("mode", "major")),\n',
    '        )\n',
    '\n',
    '\n',
    '@dataclass(slots=True)\n',
    'class ProgressionPattern:\n',
    '    chords: list[str]\n',
    '    length_bars: int\n',
    '    occurrences: int\n',
    '    coverage: float\n',
    '\n',
    '    @classmethod\n',
    '    def from_dict(cls, value: dict[str, Any]) -> ProgressionPattern:\n',
    '        return cls(\n',
    '            chords=[str(item) for item in value.get("chords", [])],\n',
    '            length_bars=int(value.get("length_bars", 1)),\n',
    '            occurrences=int(value.get("occurrences", 1)),\n',
    '            coverage=float(value.get("coverage", 0.0)),\n',
], append=False)
