from __future__ import annotations

from pathlib import Path


def put(path: str, lines: list[str], *, append: bool = False) -> None:
    target = Path(path)
    target.parent.mkdir(parents=True, exist_ok=True)
    mode = "a" if append else "w"
    with target.open(mode, encoding="utf-8", newline="") as handle:
        handle.writelines(lines)


put('src/sgchords/cli.py', [
    '        description="Estimate synchronized chords, bars, local keys, capo shapes and play-along charts.",\n',
], append=True)

put('src/sgchords/cli.py', [
    '    )\n',
    '    parser.add_argument("source", help="YouTube URL or local audio/video path")\n',
    '    parser.add_argument("-o", "--output-dir", type=Path, default=Path("sgchords-output"))\n',
    '    parser.add_argument("--detail", choices=("simple", "standard", "detailed"), default="standard")\n',
    '    parser.add_argument("--smoothing", type=float, default=0.68)\n',
    '    parser.add_argument("--meter", choices=("auto", "3", "4", "6"), default="auto")\n',
    '    parser.add_argument(\n',
    '        "--transpose", type=int, choices=range(-11, 12), default=0, metavar="[-11..11]"\n',
    '    )\n',
    '    parser.add_argument(\n',
    '        "--capo", choices=("auto", "0", "1", "2", "3", "4", "5", "6", "7"), default="auto"\n',
    '    )\n',
    '    parser.add_argument(\n',
    '        "--notation", choices=("standard", "roman", "nashville"), default="standard"\n',
    '    )\n',
    '    parser.add_argument("--instrument", choices=("guitar", "ukulele"), default="guitar")\n',
    '    return parser\n',
    '\n',
    '\n',
    'def main(argv: list[str] | None = None) -> int:\n',
    '    parser = build_parser()\n',
    '    args = parser.parse_args(argv)\n',
    '    if not 0 <= args.smoothing <= 1:\n',
    '        parser.error("--smoothing must be between 0 and 1")\n',
    '    args.output_dir.mkdir(parents=True, exist_ok=True)\n',
    '    meter = None if args.meter == "auto" else int(args.meter)\n',
    '    try:\n',
    '        result, job_dir = analyze_request(\n',
    '            youtube_url=args.source if is_youtube_url(args.source) else None,\n',
    '            upload_path=None if is_youtube_url(args.source) else args.source,\n',
    '            detail=args.detail,\n',
    '            smoothing=args.smoothing,\n',
    '            meter_override=meter,\n',
    '            workspace_root=args.output_dir / ".work",\n',
    '        )\n',
    '        suggested, _shapes, _ease = suggest_capo(result.segments, args.instrument)\n',
    '        capo = suggested if args.capo == "auto" else int(args.capo)\n',
    '        files = write_exports(\n',
    '            result,\n',
    '            args.output_dir,\n',
    '            transpose=args.transpose,\n',
    '            instrument=args.instrument,\n',
    '            capo=capo,\n',
    '            notation=args.notation,\n',
    '            meter_override=meter,\n',
    '        )\n',
    '        print(\n',
    '            render_summary(\n',
    '                result,\n',
    '                result.segments,\n',
    '                transpose=args.transpose,\n',
    '                instrument=args.instrument,\n',
    '                capo=capo,\n',
    '            )\n',
    '        )\n',
    '        print()\n',
    '        print(\n',
    '            render_bar_chart(\n',
    '                result,\n',
    '                result.segments,\n',
    '                transpose=args.transpose,\n',
    '                capo=capo,\n',
    '                notation=args.notation,\n',
    '                meter_override=meter,\n',
    '            )\n',
    '        )\n',
    '        print("\\nCreated:")\n',
    '        for path in files:\n',
    '            print(f"  {path}")\n',
    '        shutil.rmtree(job_dir, ignore_errors=True)\n',
    '        return 0\n',
    '    except Exception as exc:\n',
    '        print(f"sgchords: {exc}", file=sys.stderr)\n',
    '        return 1\n',
    '\n',
    '\n',
    'if __name__ == "__main__":\n',
    '    raise SystemExit(main())\n',
], append=True)

put('src/sgchords/exports.py', [
    'from __future__ import annotations\n',
    '\n',
    'import csv\n',
    'import json\n',
    'import re\n',
    'from collections import defaultdict\n',
    'from collections.abc import Sequence\n',
    'from dataclasses import asdict\n',
    'from pathlib import Path\n',
    'from typing import Any\n',
    '\n',
    'import numpy as np\n',
    '\n',
    'from .chords import (\n',
    '    format_chord_notation,\n',
    '    key_prefers_flats,\n',
    '    render_chord_shapes,\n',
    '    suggest_capo,\n',
    '    transpose_chord,\n',
    '    transpose_key,\n',
    ')\n',
    'from .models import AnalysisResult, BeatPoint, ChordSegment\n',
    '\n',
    '\n',
    'def safe_filename(value: str) -> str:\n',
    '    cleaned = re.sub(r"[^A-Za-z0-9._-]+", "-", value.strip()).strip("-._")\n',
    '    return (cleaned[:80] or "song").lower()\n',
    '\n',
    '\n',
    'def format_timestamp(seconds: float, *, milliseconds: bool = False) -> str:\n',
    '    seconds = max(0.0, float(seconds))\n',
    '    hours = int(seconds // 3600)\n',
    '    minutes = int(seconds % 3600 // 60)\n',
    '    remaining = seconds % 60\n',
    '    if milliseconds:\n',
    '        millis = int(round((remaining - int(remaining)) * 1000))\n',
    '        if millis == 1000:\n',
    '            remaining = int(remaining) + 1\n',
    '            millis = 0\n',
    '        return f"{hours:02d}:{minutes:02d}:{int(remaining):02d},{millis:03d}"\n',
    '    return f"{minutes + hours * 60:02d}:{remaining:05.2f}"\n',
    '\n',
    '\n',
    'def transpose_segments(\n',
    '    segments: Sequence[ChordSegment], semitones: int, *, prefer_flats: bool = False\n',
    ') -> list[ChordSegment]:\n',
    '    return [\n',
    '        ChordSegment(\n',
    '            segment.start,\n',
    '            segment.end,\n',
    '            transpose_chord(segment.chord, semitones, prefer_flats),\n',
    '            segment.confidence,\n',
    '            transpose_key(segment.local_key, semitones) if segment.local_key else None,\n',
    '            segment.bar,\n',
    '            segment.beat,\n',
    '            transpose_chord(segment.bass, semitones, prefer_flats) if segment.bass else None,\n',
    '        )\n',
    '        for segment in segments\n',
    '    ]\n',
    '\n',
    '\n',
    'def capo_shape_segments(\n',
    '    segments: Sequence[ChordSegment], capo: int, *, prefer_flats: bool = False\n',
    ') -> list[ChordSegment]:\n',
    '    return [\n',
    '        ChordSegment(\n',
    '            segment.start,\n',
    '            segment.end,\n',
    '            transpose_chord(segment.chord, -capo, prefer_flats),\n',
    '            segment.confidence,\n',
    '            segment.local_key,\n',
    '            segment.bar,\n',
    '            segment.beat,\n',
    '            transpose_chord(segment.bass, -capo, prefer_flats) if segment.bass else None,\n',
    '        )\n',
    '        for segment in segments\n',
    '    ]\n',
    '\n',
    '\n',
    'def rows_to_segments(value: Any) -> list[ChordSegment]:\n',
    '    if value is None:\n',
    '        return []\n',
    '    if hasattr(value, "to_dict"):\n',
    '        records = value.to_dict(orient="records")\n',
    '    elif isinstance(value, list) and value and isinstance(value[0], dict):\n',
    '        records = value\n',
    '    elif isinstance(value, list):\n',
    '        records = [\n',
    '            {\n',
    '                "Start (s)": row[0],\n',
    '                "End (s)": row[1],\n',
    '                "Chord": row[2],\n',
    '                "Confidence": row[3] if len(row) > 3 else 0,\n',
    '                "Local key": row[4] if len(row) > 4 else "",\n',
    '                "Bar": row[5] if len(row) > 5 else "",\n',
    '                "Beat": row[6] if len(row) > 6 else "",\n',
    '            }\n',
    '            for row in value\n',
    '            if row and len(row) >= 3\n',
    '        ]\n',
    '    else:\n',
    '        raise ValueError("The timeline table has an unsupported format.")\n',
    '\n',
    '    def pick(record: dict[str, Any], *names: str) -> Any:\n',
    '        lower = {str(key).strip().lower(): item for key, item in record.items()}\n',
    '        return next((lower[name.lower()] for name in names if name.lower() in lower), None)\n',
    '\n',
    '    segments: list[ChordSegment] = []\n',
    '    for index, record in enumerate(records, start=1):\n',
    '        try:\n',
    '            start = float(pick(record, "Start (s)", "start", "start_s"))\n',
    '            end = float(pick(record, "End (s)", "end", "end_s"))\n',
    '            chord = str(pick(record, "Chord", "chord") or "N").strip()\n',
    '            raw_confidence = pick(record, "Confidence", "confidence")\n',
    '            confidence = 0.0 if raw_confidence in {None, ""} else float(raw_confidence)\n',
    '            local_key = str(pick(record, "Local key", "local_key") or "").strip() or None\n',
    '            raw_bar = pick(record, "Bar", "bar")\n',
    '            raw_beat = pick(record, "Beat", "beat")\n',
    '            bar = (\n',
    '                None\n',
    '                if raw_bar in {None, ""} or (isinstance(raw_bar, float) and np.isnan(raw_bar))\n',
    '                else int(float(raw_bar))\n',
    '            )\n',
    '            beat = (\n',
    '                None\n',
    '                if raw_beat in {None, ""} or (isinstance(raw_beat, float) and np.isnan(raw_beat))\n',
    '                else float(raw_beat)\n',
    '            )\n',
    '        except (TypeError, ValueError) as exc:\n',
    '            raise ValueError(f"Timeline row {index} contains invalid values.") from exc\n',
    '        if start < 0 or end <= start:\n',
    '            raise ValueError(f"Timeline row {index} must have 0 <= start < end.")\n',
    '        if not chord:\n',
    '            raise ValueError(f"Timeline row {index} has an empty chord.")\n',
    '        segments.append(\n',
    '            ChordSegment(\n',
    '                start,\n',
    '                end,\n',
    '                chord,\n',
    '                float(np.clip(confidence, 0, 1)),\n',
    '                local_key,\n',
    '                bar,\n',
    '                beat,\n',
    '                chord.split("/", 1)[1] if "/" in chord else None,\n',
    '            )\n',
    '        )\n',
    '    return sorted(segments, key=lambda item: (item.start, item.end))\n',
    '\n',
    '\n',
    'def merge_adjacent_segments(segments: Sequence[ChordSegment]) -> list[ChordSegment]:\n',
    '    result: list[ChordSegment] = []\n',
    '    for segment in sorted(segments, key=lambda item: item.start):\n',
    '        if (\n',
    '            result\n',
    '            and result[-1].chord == segment.chord\n',
    '            and result[-1].local_key == segment.local_key\n',
    '            and segment.start <= result[-1].end + 0.08\n',
    '        ):\n',
    '            previous = result[-1]\n',
    '            total = previous.duration + segment.duration\n',
    '            previous.confidence = (\n',
    '                previous.confidence * previous.duration + segment.confidence * segment.duration\n',
    '            ) / max(total, 1e-9)\n',
    '            previous.end = max(previous.end, segment.end)\n',
    '        else:\n',
    '            result.append(ChordSegment.from_dict(asdict(segment)))\n',
    '    return result\n',
    '\n',
    '\n',
    'def quantize_segments(\n',
    '    segments: Sequence[ChordSegment], beats: Sequence[BeatPoint], *, duration: float\n',
    ') -> list[ChordSegment]:\n',
    '    if not segments or not beats:\n',
    '        return list(segments)\n',
    '    beat_times = np.asarray([0.0, *[beat.time for beat in beats], duration])\n',
    '    beat_times = np.unique(np.clip(beat_times, 0, duration))\n',
    '    snapped: list[ChordSegment] = []\n',
    '    for segment in segments:\n',
    '        start = float(beat_times[int(np.argmin(np.abs(beat_times - segment.start)))])\n',
    '        end = float(beat_times[int(np.argmin(np.abs(beat_times - segment.end)))])\n',
    '        if end <= start:\n',
    '            after = beat_times[beat_times > start]\n',
    '            end = float(after[0]) if after.size else duration\n',
    '        nearest = min(beats, key=lambda beat: abs(beat.time - start))\n',
    '        snapped.append(\n',
    '            ChordSegment(\n',
    '                start,\n',
    '                end,\n',
    '                segment.chord,\n',
    '                segment.confidence,\n',
    '                segment.local_key,\n',
    '                nearest.bar,\n',
    '                nearest.beat,\n',
    '                segment.bass,\n',
    '            )\n',
    '        )\n',
    '    snapped[0].start = 0.0\n',
    '    snapped[-1].end = duration\n',
    '    for index in range(1, len(snapped)):\n',
    '        midpoint = (snapped[index - 1].end + snapped[index].start) / 2\n',
    '        snapped[index - 1].end = snapped[index].start = midpoint\n',
    '    return merge_adjacent_segments(snapped)\n',
    '\n',
    '\n',
    'def _chord_at_time(segments: Sequence[ChordSegment], timestamp: float) -> ChordSegment | None:\n',
    '    return next((segment for segment in segments if segment.start <= timestamp < segment.end), None)\n',
    '\n',
    '\n',
    'def render_bar_chart(\n',
    '    result: AnalysisResult,\n',
    '    segments: Sequence[ChordSegment],\n',
    '    *,\n',
    '    transpose: int = 0,\n',
    '    capo: int = 0,\n',
    '    notation: str = "standard",\n',
    '    meter_override: int | None = None,\n',
    ') -> str:\n',
    '    target_key = transpose_key(result.key, transpose)\n',
    '    flats = key_prefers_flats(target_key)\n',
], append=False)
