from __future__ import annotations

from pathlib import Path


def put(path: str, lines: list[str], *, append: bool = False) -> None:
    target = Path(path)
    target.parent.mkdir(parents=True, exist_ok=True)
    mode = "a" if append else "w"
    with target.open(mode, encoding="utf-8", newline="") as handle:
        handle.writelines(lines)


put('src/sgchords/analyzer.py', [
    '            spec = specs[state - 1]\n',
], append=True)

put('src/sgchords/analyzer.py', [
    '            label = transpose_chord(spec.label, 0, flats)\n',
    '            bass_mass = np.maximum(bass[index], 0)\n',
    '            bass_mass /= float(np.sum(bass_mass)) + 1e-12\n',
    '            order = np.argsort(bass_mass)[::-1]\n',
    '            bass_pitch = int(order[0])\n',
    '            margin = float(bass_mass[order[0]] - bass_mass[order[1]])\n',
    '            tones = {(spec.root + interval) % 12 for interval in spec.intervals}\n',
    '            if (\n',
    '                bass_pitch != spec.root\n',
    '                and bass_pitch in tones\n',
    '                and bass_mass[bass_pitch] >= 0.27\n',
    '                and margin >= 0.05\n',
    '            ):\n',
    '                label += f"/{pitch_name(bass_pitch, flats)}"\n',
    '        labels.append(label)\n',
    '        row = emissions[index]\n',
    '        runner_up = float(np.max(np.delete(row, int(state)))) if len(row) > 1 else float(row[state])\n',
    '        margin = float(row[state] - runner_up)\n',
    '        energy_factor = float(np.clip(energy[index] / (median_energy + 1e-12), 0, 1))\n',
    '        confidences.append(\n',
    '            float(\n',
    '                np.clip(\n',
    '                    0.34 + 1.75 * margin + 0.18 * tonalities[index] + 0.08 * energy_factor,\n',
    '                    0.05,\n',
    '                    0.99,\n',
    '                )\n',
    '            )\n',
    '        )\n',
    '    return labels, confidences, tonalities, states\n',
    '\n',
    '\n',
    'def _repair_chord_blips(\n',
    '    labels: list[str], confidences: list[float], boundaries: np.ndarray\n',
    ') -> list[str]:\n',
    '    repaired = labels.copy()\n',
    '    for index in range(1, len(labels) - 1):\n',
    '        duration = boundaries[index + 1] - boundaries[index]\n',
    '        if labels[index - 1] == labels[index + 1] != labels[index] and (\n',
    '            duration < 0.9 or confidences[index] < 0.48\n',
    '        ):\n',
    '            repaired[index] = labels[index - 1]\n',
    '    return repaired\n',
    '\n',
    '\n',
    'def _position_at(timestamp: float, beats: Sequence[BeatPoint]) -> tuple[int | None, float | None]:\n',
    '    if not beats:\n',
    '        return None, None\n',
    '    index = int(np.argmin([abs(beat.time - timestamp) for beat in beats]))\n',
    '    return beats[index].bar, beats[index].beat\n',
    '\n',
    '\n',
    'def _merge_segments(segments: Sequence[ChordSegment]) -> list[ChordSegment]:\n',
    '    merged: list[ChordSegment] = []\n',
    '    for segment in segments:\n',
    '        if segment.end <= segment.start:\n',
    '            continue\n',
    '        if (\n',
    '            merged\n',
    '            and merged[-1].chord == segment.chord\n',
    '            and merged[-1].local_key == segment.local_key\n',
    '        ):\n',
    '            previous = merged[-1]\n',
    '            total = previous.duration + segment.duration\n',
    '            previous.confidence = (\n',
    '                previous.confidence * previous.duration + segment.confidence * segment.duration\n',
    '            ) / max(total, 1e-9)\n',
    '            previous.end = segment.end\n',
    '        else:\n',
    '            merged.append(segment)\n',
    '    return merged\n',
    '\n',
    '\n',
    'def _chord_at_time(segments: Sequence[ChordSegment], timestamp: float) -> str:\n',
    '    for segment in segments:\n',
    '        if segment.start <= timestamp < segment.end:\n',
    '            return simplify_chord(segment.chord)\n',
    '    return "N"\n',
    '\n',
    '\n',
    'def detect_progression_patterns(\n',
    '    segments: Sequence[ChordSegment], beats: Sequence[BeatPoint], meter: int\n',
    ') -> list[ProgressionPattern]:\n',
    '    if not segments or len(beats) < meter * 4:\n',
    '        return []\n',
    '    bar_starts = [beat.time for beat in beats if beat.downbeat]\n',
    '    if len(bar_starts) < 4:\n',
    '        return []\n',
    '    bars: list[tuple[str, ...]] = []\n',
    '    for start_index, start in enumerate(bar_starts):\n',
    '        end = bar_starts[start_index + 1] if start_index + 1 < len(bar_starts) else segments[-1].end\n',
    '        samples = np.linspace(start, max(start, end - 1e-4), meter)\n',
    '        bar = tuple(_chord_at_time(segments, float(value)) for value in samples)\n',
    '        # Compress repeated beat labels within each bar.\n',
    '        bars.append(\n',
    '            tuple(chord for index, chord in enumerate(bar) if index == 0 or chord != bar[index - 1])\n',
    '        )\n',
    '    patterns: list[ProgressionPattern] = []\n',
    '    for length in (1, 2, 4):\n',
    '        if len(bars) < length * 2:\n',
    '            continue\n',
    '        windows = [\n',
    '            tuple(chord for bar in bars[index : index + length] for chord in bar)\n',
    '            for index in range(0, len(bars) - length + 1, length)\n',
    '        ]\n',
    '        counts = Counter(windows)\n',
    '        sequence, occurrences = counts.most_common(1)[0]\n',
    '        if occurrences >= 2 and sequence:\n',
    '            patterns.append(\n',
    '                ProgressionPattern(\n',
    '                    list(sequence), length, occurrences, min(1.0, occurrences * length / len(bars))\n',
    '                )\n',
    '            )\n',
    '    patterns.sort(\n',
    '        key=lambda item: (item.coverage, item.occurrences, item.length_bars), reverse=True\n',
    '    )\n',
    '    return patterns[:3]\n',
    '\n',
    '\n',
    'def _diatonic_duration_ratio(\n',
    '    segments: Sequence[ChordSegment], key_root: int, key_mode: str, detail: str\n',
    ') -> float | None:\n',
    '    specs = chord_vocabulary(detail)\n',
    '    by_simple: dict[str, ChordSpec] = {}\n',
    '    for spec in specs:\n',
    '        by_simple.setdefault(simplify_chord(spec.label), spec)\n',
    '    total = diatonic = 0.0\n',
    '    for segment in segments:\n',
    '        if segment.chord == "N":\n',
    '            continue\n',
    '        total += segment.duration\n',
    '        spec = by_simple.get(simplify_chord(segment.chord))\n',
    '        if spec and is_diatonic(spec, key_root, key_mode):\n',
    '            diatonic += segment.duration\n',
    '    return None if total <= 0 else diatonic / total\n',
    '\n',
    '\n',
    'def analyze_audio(\n',
    '    audio_path: str | Path,\n',
    '    *,\n',
    '    detail: str = "standard",\n',
    '    smoothing: float = 0.68,\n',
    '    meter_override: int | None = None,\n',
    '    config: AnalyzerConfig | None = None,\n',
    ') -> AnalyzerOutput:\n',
    '    config = config or AnalyzerConfig()\n',
    '    y, sample_rate = _load_audio(audio_path, config.sample_rate)\n',
    '    duration = float(len(y) / sample_rate) if sample_rate else 0.0\n',
    '    if duration < config.min_audio_seconds:\n',
    '        raise AnalysisError(\n',
    '            f"The song must be at least {config.min_audio_seconds:.0f} seconds long."\n',
    '        )\n',
    '    peak = float(np.max(np.abs(y))) if y.size else 0.0\n',
    '    if peak < 1e-5:\n',
    '        raise AnalysisError("The audio is silent or too quiet to analyze.")\n',
    '    y = y / peak\n',
    '    warnings: list[str] = []\n',
    '    try:\n',
    '        harmonic = librosa.effects.harmonic(y, margin=2.5)\n',
    '    except Exception:\n',
    '        harmonic = y\n',
    '        warnings.append("Harmonic/percussive separation failed; the raw mix was analyzed.")\n',
    '    try:\n',
    '        tuning = float(\n',
    '            librosa.estimate_tuning(y=harmonic, sr=sample_rate, bins_per_octave=12, resolution=0.01)\n',
    '        )\n',
    '        if not np.isfinite(tuning):\n',
    '            tuning = 0.0\n',
    '    except Exception:\n',
    '        tuning = 0.0\n',
    '    tuning_cents = float(np.clip(tuning * 100, -50, 50))\n',
    '    try:\n',
    '        chroma = librosa.feature.chroma_cqt(\n',
    '            y=harmonic,\n',
    '            sr=sample_rate,\n',
    '            hop_length=config.hop_length,\n',
    '            bins_per_octave=36,\n',
    '            n_octaves=6,\n',
    '            tuning=tuning * 3,\n',
    '            norm=2,\n',
    '            cqt_mode="hybrid",\n',
    '        )\n',
    '    except Exception:\n',
    '        chroma = librosa.feature.chroma_stft(\n',
    '            y=harmonic,\n',
    '            sr=sample_rate,\n',
    '            hop_length=config.hop_length,\n',
    '            n_fft=4096,\n',
    '            tuning=tuning,\n',
    '            norm=2,\n',
    '        )\n',
    '        warnings.append("Constant-Q analysis failed; an STFT chromagram fallback was used.")\n',
    '    try:\n',
    '        bass_audio = _lowpass(harmonic, sample_rate)\n',
    '        bass_chroma = librosa.feature.chroma_cqt(\n',
    '            y=bass_audio,\n',
    '            sr=sample_rate,\n',
    '            hop_length=config.hop_length,\n',
    '            fmin=librosa.note_to_hz("C1"),\n',
    '            n_octaves=4,\n',
    '            bins_per_octave=36,\n',
    '            tuning=tuning * 3,\n',
    '            norm=2,\n',
    '            cqt_mode="hybrid",\n',
    '        )\n',
    '    except Exception:\n',
    '        bass_chroma = chroma\n',
    '        warnings.append("Bass-note isolation failed; slash-chord labels are less reliable.")\n',
    '    rms = librosa.feature.rms(y=y, frame_length=2048, hop_length=config.hop_length)[0]\n',
    '    onset = librosa.onset.onset_strength(\n',
    '        y=y, sr=sample_rate, hop_length=config.hop_length, aggregate=np.median\n',
    '    )\n',
    '    tempo, beat_frames, tempo_confidence = _estimate_beats(\n',
    '        onset, sample_rate=sample_rate, hop_length=config.hop_length\n',
    '    )\n',
    '    tracked_beats = beat_frames.size >= 3\n',
    '    if tracked_beats:\n',
    '        novelty = _harmonic_novelty(chroma, onset)\n',
    '        beat_frames = _refine_beat_frames(beat_frames, novelty, config.boundary_search_ratio)\n',
    '        beat_times = librosa.frames_to_time(\n',
    '            beat_frames, sr=sample_rate, hop_length=config.hop_length\n',
    '        )\n',
    '        beat_strengths = onset[np.clip(beat_frames, 0, max(0, len(onset) - 1))]\n',
    '        meter, phase, meter_confidence = _estimate_meter(beat_strengths, meter_override)\n',
    '    else:\n',
    '        # Keep charts and the synchronized editor usable even when a beat tracker cannot lock.\n',
    '        # This is explicitly marked as a low-confidence fixed grid rather than a detected tempo.\n',
    '        beat_times = np.arange(0.0, duration, config.fallback_window_seconds)\n',
    '        beat_strengths = np.zeros(len(beat_times), dtype=float)\n',
    '        meter = int(meter_override) if meter_override in {3, 4, 6} else 4\n',
    '        phase = 0\n',
    '        meter_confidence = 1.0 if meter_override in {3, 4, 6} else 0.0\n',
    '    beats = [\n',
    '        BeatPoint(\n',
    '            float(time),\n',
    '            index,\n',
    '            (index - phase) // meter + 1 if index >= phase else 1,\n',
    '            float((index - phase) % meter + 1),\n',
    '            float(beat_strengths[index] / (float(np.max(beat_strengths)) + 1e-12))\n',
    '            if beat_strengths.size\n',
    '            else 0.0,\n',
    '            (index - phase) % meter == 0,\n',
    '        )\n',
    '        for index, time in enumerate(beat_times)\n',
    '    ]\n',
    '    boundaries, _grid_available = _segment_boundaries(duration, beat_times, config)\n',
    '    used_beats = tracked_beats\n',
    '    if not used_beats:\n',
    '        warnings.append(\n',
    '            "A stable beat grid was not found; a fixed practice grid was used for charting."\n',
    '        )\n',
    '    vectors, bass_vectors, energies = _aggregate_features(\n',
    '        chroma, bass_chroma, rms, boundaries, sample_rate=sample_rate, hop_length=config.hop_length\n',
    '    )\n',
    '    drone_root, drone_confidence, corrected = detect_drone(vectors, energies)\n',
    '    local_keys, key_regions, dominant_key, key_confidence = estimate_local_keys(\n',
    '        corrected,\n',
    '        energies,\n',
    '        boundaries,\n',
    '        window_seconds=config.local_key_window_seconds,\n',
    '        min_region_seconds=config.local_key_min_region_seconds,\n',
    '    )\n',
    '    labels, confidences, tonalities, _states = classify_chroma_segments(\n',
    '        corrected,\n',
    '        energies,\n',
    '        bass_vectors=bass_vectors,\n',
    '        detail=detail,\n',
    '        smoothing=smoothing,\n',
    '        local_keys=local_keys,\n',
    '    )\n',
    '    labels = _repair_chord_blips(labels, confidences, boundaries)\n',
    '    raw_segments: list[ChordSegment] = []\n',
    '    for index, label in enumerate(labels):\n',
    '        bar, beat = _position_at(float(boundaries[index]), beats)\n',
    '        parsed_bass = label.split("/", 1)[1] if "/" in label else None\n',
    '        raw_segments.append(\n',
    '            ChordSegment(\n',
    '                float(boundaries[index]),\n',
    '                float(boundaries[index + 1]),\n',
    '                label,\n',
    '                confidences[index],\n',
], append=True)
