from __future__ import annotations

from pathlib import Path


def put(path: str, lines: list[str], *, append: bool = False) -> None:
    target = Path(path)
    target.parent.mkdir(parents=True, exist_ok=True)
    mode = "a" if append else "w"
    with target.open(mode, encoding="utf-8", newline="") as handle:
        handle.writelines(lines)


put('src/sgchords/chords.py', [
    '    "major": (0, 2, 4, 5, 7, 9, 11),\n',
], append=True)

put('src/sgchords/chords.py', [
    '    "minor": (0, 2, 3, 5, 7, 8, 10),\n',
    '    "dorian": (0, 2, 3, 5, 7, 9, 10),\n',
    '    "mixolydian": (0, 2, 4, 5, 7, 9, 10),\n',
    '    "phrygian": (0, 1, 3, 5, 7, 8, 10),\n',
    '}\n',
    '\n',
    'MODE_PROFILES: dict[str, np.ndarray] = {\n',
    '    "major": np.asarray([6.35, 2.23, 3.48, 2.33, 4.38, 4.09, 2.52, 5.19, 2.39, 3.66, 2.29, 2.88]),\n',
    '    "minor": np.asarray([6.33, 2.68, 3.52, 5.38, 2.60, 3.53, 2.54, 4.75, 3.98, 2.69, 3.34, 3.17]),\n',
    '    "dorian": np.asarray([6.15, 2.75, 3.70, 5.10, 2.20, 3.75, 2.35, 4.95, 2.35, 4.15, 3.70, 2.20]),\n',
    '    "mixolydian": np.asarray(\n',
    '        [6.20, 2.15, 3.55, 2.20, 4.15, 4.05, 2.25, 5.25, 2.20, 3.65, 4.05, 2.15]\n',
    '    ),\n',
    '    "phrygian": np.asarray(\n',
    '        [6.15, 4.35, 2.25, 4.60, 2.00, 3.65, 2.10, 4.95, 3.90, 2.00, 3.65, 2.05]\n',
    '    ),\n',
    '}\n',
    '\n',
    '_CHORD_RE = re.compile(r"^\\s*([A-Ga-g])([#b]?)([^/]*?)(?:/([A-Ga-g])([#b]?))?\\s*$")\n',
    '_KEY_RE = re.compile(r"^\\s*([A-Ga-g])([#b]?)\\s+(major|minor|dorian|mixolydian|phrygian)\\s*$", re.I)\n',
    '\n',
    '\n',
    '@dataclass(frozen=True, slots=True)\n',
    'class ParsedChord:\n',
    '    root: int\n',
    '    suffix: str\n',
    '    bass: int | None = None\n',
    '\n',
    '\n',
    '@dataclass(frozen=True, slots=True)\n',
    'class ChordSpec:\n',
    '    label: str\n',
    '    root: int\n',
    '    quality: str\n',
    '    intervals: tuple[int, ...]\n',
    '    weights: tuple[float, ...]\n',
    '\n',
    '\n',
    '@dataclass(frozen=True, slots=True)\n',
    'class TonalityCandidate:\n',
    '    root: int\n',
    '    mode: str\n',
    '    label: str\n',
    '\n',
    '\n',
    'QUALITY_DEFINITIONS: dict[str, tuple[tuple[int, ...], tuple[float, ...], str]] = {\n',
    '    "maj": ((0, 4, 7), (1.00, 0.86, 0.72), ""),\n',
    '    "min": ((0, 3, 7), (1.00, 0.86, 0.72), "m"),\n',
    '    "7": ((0, 4, 7, 10), (1.00, 0.82, 0.68, 0.58), "7"),\n',
    '    "maj7": ((0, 4, 7, 11), (1.00, 0.82, 0.68, 0.55), "maj7"),\n',
    '    "min7": ((0, 3, 7, 10), (1.00, 0.82, 0.68, 0.56), "m7"),\n',
    '    "sus2": ((0, 2, 7), (1.00, 0.78, 0.72), "sus2"),\n',
    '    "sus4": ((0, 5, 7), (1.00, 0.78, 0.72), "sus4"),\n',
    '    "dim": ((0, 3, 6), (1.00, 0.82, 0.68), "dim"),\n',
    '    "aug": ((0, 4, 8), (1.00, 0.82, 0.68), "aug"),\n',
    '    "6": ((0, 4, 7, 9), (1.00, 0.82, 0.68, 0.52), "6"),\n',
    '    "min6": ((0, 3, 7, 9), (1.00, 0.82, 0.68, 0.52), "m6"),\n',
    '    "add9": ((0, 2, 4, 7), (1.00, 0.48, 0.82, 0.68), "add9"),\n',
    '    "power": ((0, 7), (1.00, 0.76), "5"),\n',
    '}\n',
    'SIMPLE_QUALITIES = ("maj", "min")\n',
    'STANDARD_QUALITIES = ("maj", "min", "7", "maj7", "min7", "sus2", "sus4", "dim")\n',
    'DETAILED_QUALITIES = STANDARD_QUALITIES + ("aug", "6", "min6", "add9", "power")\n',
    '\n',
    '# Common, playable voicings. Guitar is EADGBE; ukulele is GCEA.\n',
    'GUITAR_SHAPES: dict[str, str] = {\n',
    '    "C": "x32010",\n',
    '    "C7": "x32310",\n',
    '    "Cmaj7": "x32000",\n',
    '    "Cm": "x35543",\n',
    '    "Csus2": "x30013",\n',
    '    "Csus4": "x33011",\n',
    '    "D": "xx0232",\n',
    '    "Dm": "xx0231",\n',
    '    "D7": "xx0212",\n',
    '    "Dmaj7": "xx0222",\n',
    '    "Dsus2": "xx0230",\n',
    '    "Dsus4": "xx0233",\n',
    '    "E": "022100",\n',
    '    "Em": "022000",\n',
    '    "E7": "020100",\n',
    '    "Emaj7": "021100",\n',
    '    "Esus4": "022200",\n',
    '    "F": "133211",\n',
    '    "Fm": "133111",\n',
    '    "Fmaj7": "xx3210",\n',
    '    "G": "320003",\n',
    '    "Gm": "355333",\n',
    '    "G7": "320001",\n',
    '    "Gmaj7": "320002",\n',
    '    "Gsus4": "330013",\n',
    '    "A": "x02220",\n',
    '    "Am": "x02210",\n',
    '    "A7": "x02020",\n',
    '    "Amaj7": "x02120",\n',
    '    "Asus2": "x02200",\n',
    '    "Asus4": "x02230",\n',
    '    "Bb": "x13331",\n',
    '    "Bbm": "x13321",\n',
    '    "Bb7": "x13131",\n',
    '    "B": "x24442",\n',
    '    "Bm": "x24432",\n',
    '    "B7": "x21202",\n',
    '    "Bmaj7": "x24342",\n',
    '    "F#": "244322",\n',
    '    "F#m": "244222",\n',
    '    "F#7": "242322",\n',
    '    "Db": "x46664",\n',
    '    "Dbm": "x46654",\n',
    '    "Eb": "x68886",\n',
    '    "Ebm": "x68876",\n',
    '    "Ab": "466544",\n',
    '    "Abm": "466444",\n',
    '}\n',
    'UKULELE_SHAPES: dict[str, str] = {\n',
    '    "C": "0003",\n',
    '    "Cm": "0333",\n',
    '    "C7": "0001",\n',
    '    "Cmaj7": "0002",\n',
    '    "Csus2": "0233",\n',
    '    "Csus4": "0013",\n',
    '    "D": "2220",\n',
    '    "Dm": "2210",\n',
    '    "D7": "2223",\n',
    '    "Dmaj7": "2224",\n',
    '    "Dsus2": "2200",\n',
    '    "Dsus4": "0230",\n',
    '    "E": "1402",\n',
    '    "Em": "0432",\n',
    '    "E7": "1202",\n',
    '    "Emaj7": "1302",\n',
    '    "F": "2010",\n',
    '    "Fm": "1013",\n',
    '    "F7": "2310",\n',
    '    "Fmaj7": "2410",\n',
    '    "G": "0232",\n',
    '    "Gm": "0231",\n',
    '    "G7": "0212",\n',
    '    "Gmaj7": "0222",\n',
    '    "Gsus4": "0233",\n',
    '    "A": "2100",\n',
    '    "Am": "2000",\n',
    '    "A7": "0100",\n',
    '    "Amaj7": "1100",\n',
    '    "Asus2": "2452",\n',
    '    "Asus4": "2200",\n',
    '    "Bb": "3211",\n',
    '    "Bbm": "3111",\n',
    '    "Bb7": "1211",\n',
    '    "B": "4322",\n',
    '    "Bm": "4222",\n',
    '    "B7": "2322",\n',
    '    "F#": "3121",\n',
    '    "F#m": "2120",\n',
    '    "Db": "1114",\n',
    '    "Dbm": "1104",\n',
    '    "Eb": "0331",\n',
    '    "Ebm": "3321",\n',
    '    "Ab": "5343",\n',
    '    "Abm": "4342",\n',
    '}\n',
    '\n',
    'GUITAR_EASY = {\n',
    '    "C",\n',
    '    "C7",\n',
    '    "Cmaj7",\n',
    '    "D",\n',
    '    "Dm",\n',
    '    "D7",\n',
    '    "E",\n',
    '    "Em",\n',
    '    "E7",\n',
    '    "Fmaj7",\n',
    '    "G",\n',
    '    "G7",\n',
    '    "A",\n',
    '    "Am",\n',
    '    "A7",\n',
    '    "B7",\n',
    '}\n',
    'UKULELE_EASY = {\n',
    '    "C",\n',
    '    "C7",\n',
    '    "Cmaj7",\n',
    '    "D",\n',
    '    "Dm",\n',
    '    "D7",\n',
    '    "E7",\n',
    '    "Em",\n',
    '    "F",\n',
    '    "Fmaj7",\n',
    '    "G",\n',
    '    "G7",\n',
    '    "A",\n',
    '    "Am",\n',
    '    "A7",\n',
    '    "Bb",\n',
    '    "B7",\n',
    '}\n',
    '\n',
    '\n',
    'def pitch_name(pitch_class: int, prefer_flats: bool = False) -> str:\n',
    '    return (FLAT_NAMES if prefer_flats else SHARP_NAMES)[pitch_class % 12]\n',
    '\n',
    '\n',
    'def _mode_prefers_flats(root: int, mode: str) -> bool:\n',
    '    flat_roots = {\n',
    '        "major": {1, 3, 5, 6, 8, 10},\n',
    '        "minor": {0, 2, 3, 5, 7, 10},\n',
    '        "dorian": {0, 2, 5, 7, 10},\n',
    '        "mixolydian": {0, 2, 5, 7, 10},\n',
    '        "phrygian": {0, 3, 5, 7, 10},\n',
    '    }\n',
    '    return root in flat_roots.get(mode, set())\n',
    '\n',
    '\n',
    'def key_name(pitch_class: int, mode: str) -> str:\n',
    '    return f"{pitch_name(pitch_class, _mode_prefers_flats(pitch_class % 12, mode))} {mode}"\n',
    '\n',
    '\n',
    'def parse_key(key: str) -> tuple[int, str] | None:\n',
    '    match = _KEY_RE.match(key)\n',
    '    if match is None:\n',
    '        return None\n',
    '    return PITCH_CLASS[match.group(1).upper() + match.group(2)], match.group(3).lower()\n',
    '\n',
    '\n',
    'def key_prefers_flats(key: str) -> bool:\n',
    '    parsed = parse_key(key)\n',
    '    return bool(parsed and _mode_prefers_flats(*parsed))\n',
    '\n',
    '\n',
    'def parse_chord(chord: str) -> ParsedChord | None:\n',
    '    if not chord or chord.strip().upper() in {"N", "NC", "N.C.", "NO CHORD"}:\n',
    '        return None\n',
    '    match = _CHORD_RE.match(chord)\n',
    '    if match is None:\n',
    '        return None\n',
    '    root = PITCH_CLASS.get(match.group(1).upper() + match.group(2))\n',
    '    if root is None:\n',
    '        return None\n',
    '    bass_name = (match.group(4) or "").upper() + (match.group(5) or "")\n',
    '    return ParsedChord(\n',
    '        root, match.group(3).strip(), PITCH_CLASS.get(bass_name) if bass_name else None\n',
    '    )\n',
    '\n',
    '\n',
    'def transpose_chord(chord: str, semitones: int, prefer_flats: bool = False) -> str:\n',
    '    parsed = parse_chord(chord)\n',
    '    if parsed is None:\n',
    '        return "N" if chord.strip().upper() in {"N", "NC", "N.C.", "NO CHORD"} else chord\n',
    '    label = f"{pitch_name(parsed.root + semitones, prefer_flats)}{parsed.suffix}"\n',
    '    if parsed.bass is not None:\n',
    '        label += f"/{pitch_name(parsed.bass + semitones, prefer_flats)}"\n',
    '    return label\n',
    '\n',
    '\n',
    'def _suffix_quality(suffix: str) -> str:\n',
    '    lower = suffix.lower().strip()\n',
    '    if lower in {"", "maj"}:\n',
    '        return "maj"\n',
    '    if lower.startswith("maj7"):\n',
    '        return "maj7"\n',
    '    if lower.startswith(("m7", "min7")):\n',
    '        return "min7"\n',
    '    if lower.startswith(("m6", "min6")):\n',
    '        return "min6"\n',
    '    if lower.startswith(("m", "min")):\n',
    '        return "min"\n',
    '    if lower.startswith("dim") or "°" in lower:\n',
    '        return "dim"\n',
    '    if lower.startswith("aug") or "+" in lower:\n',
    '        return "aug"\n',
    '    if lower.startswith("sus2"):\n',
    '        return "sus2"\n',
    '    if lower.startswith("sus"):\n',
    '        return "sus4"\n',
    '    if lower.startswith("add9"):\n',
    '        return "add9"\n',
    '    if lower == "5":\n',
    '        return "power"\n',
    '    if lower.startswith("7"):\n',
    '        return "7"\n',
    '    if lower.startswith("6"):\n',
    '        return "6"\n',
    '    return "maj"\n',
    '\n',
    '\n',
    'def simplify_chord(chord: str, *, keep_bass: bool = False) -> str:\n',
    '    parsed = parse_chord(chord)\n',
    '    if parsed is None:\n',
    '        return "N" if chord.strip().upper() in {"N", "NC", "N.C.", "NO CHORD"} else chord\n',
    '    suffix = "m" if _suffix_quality(parsed.suffix) in {"min", "min7", "min6"} else ""\n',
    '    flats = "b" in chord[:2]\n',
    '    label = f"{pitch_name(parsed.root, flats)}{suffix}"\n',
    '    if keep_bass and parsed.bass is not None:\n',
    '        label += f"/{pitch_name(parsed.bass, flats)}"\n',
    '    return label\n',
    '\n',
    '\n',
    'def transpose_key(key: str, semitones: int) -> str:\n',
    '    parsed = parse_key(key)\n',
    '    return key if parsed is None else key_name(parsed[0] + semitones, parsed[1])\n',
    '\n',
    '\n',
    '@lru_cache(maxsize=6)\n',
    'def chord_vocabulary(detail: str = "standard") -> tuple[ChordSpec, ...]:\n',
    '    qualities = {\n',
    '        "simple": SIMPLE_QUALITIES,\n',
    '        "standard": STANDARD_QUALITIES,\n',
    '        "detailed": DETAILED_QUALITIES,\n',
    '    }.get(detail.lower())\n',
    '    if qualities is None:\n',
    '        raise ValueError(f"Unknown chord vocabulary: {detail}")\n',
    '    result: list[ChordSpec] = []\n',
    '    for root in range(12):\n',
    '        for quality in qualities:\n',
    '            intervals, weights, suffix = QUALITY_DEFINITIONS[quality]\n',
    '            result.append(\n',
    '                ChordSpec(f"{SHARP_NAMES[root]}{suffix}", root, quality, intervals, weights)\n',
    '            )\n',
    '    return tuple(result)\n',
    '\n',
    '\n',
    'def chord_template(spec: ChordSpec) -> np.ndarray:\n',
    '    template = np.zeros(12, dtype=float)\n',
    '    for interval, weight in zip(spec.intervals, spec.weights, strict=True):\n',
    '        template[(spec.root + interval) % 12] = weight\n',
    '    return template / (float(np.linalg.norm(template)) + 1e-12)\n',
    '\n',
    '\n',
    '@lru_cache(maxsize=2)\n',
    'def tonality_candidates(include_phrygian: bool = True) -> tuple[TonalityCandidate, ...]:\n',
    '    modes = (\n',
    '        ("major", "minor", "dorian", "mixolydian", "phrygian")\n',
    '        if include_phrygian\n',
    '        else ("major", "minor", "dorian", "mixolydian")\n',
    '    )\n',
    '    return tuple(\n',
    '        TonalityCandidate(root, mode, key_name(root, mode)) for mode in modes for root in range(12)\n',
    '    )\n',
    '\n',
    '\n',
    'def tonality_scores(\n',
    '    chroma: np.ndarray, *, include_phrygian: bool = True\n',
    ') -> tuple[tuple[TonalityCandidate, ...], np.ndarray]:\n',
    '    values = np.nan_to_num(np.asarray(chroma, dtype=float).reshape(12))\n',
    '    if float(np.sum(np.maximum(values, 0))) <= 1e-10:\n',
    '        return tonality_candidates(include_phrygian), np.zeros(\n',
    '            len(tonality_candidates(include_phrygian))\n',
    '        )\n',
    '    normalized = (values - np.mean(values)) / (np.std(values) + 1e-9)\n',
    '    candidates = tonality_candidates(include_phrygian)\n',
    '    scores: list[float] = []\n',
    '    for candidate in candidates:\n',
    '        profile = np.roll(MODE_PROFILES[candidate.mode], candidate.root)\n',
    '        profile = (profile - np.mean(profile)) / (np.std(profile) + 1e-9)\n',
    '        score = float(np.dot(normalized, profile) / 12)\n',
], append=True)
